// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: byteplus/vod/business/vod_common.proto

package com.byteplus.service.vod.model.business;

/**
 * Protobuf type {@code Byteplus.Vod.Models.Business.AdaptiveBitrateStreamingInfo}
 */
public final class AdaptiveBitrateStreamingInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Byteplus.Vod.Models.Business.AdaptiveBitrateStreamingInfo)
    AdaptiveBitrateStreamingInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AdaptiveBitrateStreamingInfo.newBuilder() to construct.
  private AdaptiveBitrateStreamingInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AdaptiveBitrateStreamingInfo() {
    mainPlayUrl_ = "";
    backupPlayUrl_ = "";
    abrFormat_ = "";
    playAuth_ = "";
    playAuthId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AdaptiveBitrateStreamingInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AdaptiveBitrateStreamingInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            mainPlayUrl_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            backupPlayUrl_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            abrFormat_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            playAuth_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            playAuthId_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.byteplus.service.vod.model.business.VodCommon.internal_static_Byteplus_Vod_Models_Business_AdaptiveBitrateStreamingInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.byteplus.service.vod.model.business.VodCommon.internal_static_Byteplus_Vod_Models_Business_AdaptiveBitrateStreamingInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.byteplus.service.vod.model.business.AdaptiveBitrateStreamingInfo.class, com.byteplus.service.vod.model.business.AdaptiveBitrateStreamingInfo.Builder.class);
  }

  public static final int MAINPLAYURL_FIELD_NUMBER = 1;
  private volatile java.lang.Object mainPlayUrl_;
  /**
   * <pre>
   *主文件主播放地址
   *下发Abr hls时，为主文件主播放地址
   *下发Abr Dash时，为空字符串
   *没有别的场景
   * </pre>
   *
   * <code>string MainPlayUrl = 1;</code>
   * @return The mainPlayUrl.
   */
  @java.lang.Override
  public java.lang.String getMainPlayUrl() {
    java.lang.Object ref = mainPlayUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mainPlayUrl_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *主文件主播放地址
   *下发Abr hls时，为主文件主播放地址
   *下发Abr Dash时，为空字符串
   *没有别的场景
   * </pre>
   *
   * <code>string MainPlayUrl = 1;</code>
   * @return The bytes for mainPlayUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMainPlayUrlBytes() {
    java.lang.Object ref = mainPlayUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mainPlayUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BACKUPPLAYURL_FIELD_NUMBER = 2;
  private volatile java.lang.Object backupPlayUrl_;
  /**
   * <pre>
   *主文件备播放地址
   *下发Abr hls时，为主文件备播放地址
   *下发Abr Dash时，为空字符串
   *没有别的场景
   * </pre>
   *
   * <code>string BackupPlayUrl = 2;</code>
   * @return The backupPlayUrl.
   */
  @java.lang.Override
  public java.lang.String getBackupPlayUrl() {
    java.lang.Object ref = backupPlayUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      backupPlayUrl_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *主文件备播放地址
   *下发Abr hls时，为主文件备播放地址
   *下发Abr Dash时，为空字符串
   *没有别的场景
   * </pre>
   *
   * <code>string BackupPlayUrl = 2;</code>
   * @return The bytes for backupPlayUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBackupPlayUrlBytes() {
    java.lang.Object ref = backupPlayUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      backupPlayUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ABRFORMAT_FIELD_NUMBER = 3;
  private volatile java.lang.Object abrFormat_;
  /**
   * <pre>
   *标识本次下发的ABR码流Format
   *下发Abr hls时，AbrFormat=hls
   *下发Abr Dash时，AbrFormat=dash
   *没有别的场景
   * </pre>
   *
   * <code>string AbrFormat = 3;</code>
   * @return The abrFormat.
   */
  @java.lang.Override
  public java.lang.String getAbrFormat() {
    java.lang.Object ref = abrFormat_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      abrFormat_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *标识本次下发的ABR码流Format
   *下发Abr hls时，AbrFormat=hls
   *下发Abr Dash时，AbrFormat=dash
   *没有别的场景
   * </pre>
   *
   * <code>string AbrFormat = 3;</code>
   * @return The bytes for abrFormat.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAbrFormatBytes() {
    java.lang.Object ref = abrFormat_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      abrFormat_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PLAYAUTH_FIELD_NUMBER = 4;
  private volatile java.lang.Object playAuth_;
  /**
   * <code>string PlayAuth = 4;</code>
   * @return The playAuth.
   */
  @java.lang.Override
  public java.lang.String getPlayAuth() {
    java.lang.Object ref = playAuth_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      playAuth_ = s;
      return s;
    }
  }
  /**
   * <code>string PlayAuth = 4;</code>
   * @return The bytes for playAuth.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPlayAuthBytes() {
    java.lang.Object ref = playAuth_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      playAuth_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PLAYAUTHID_FIELD_NUMBER = 5;
  private volatile java.lang.Object playAuthId_;
  /**
   * <code>string PlayAuthId = 5;</code>
   * @return The playAuthId.
   */
  @java.lang.Override
  public java.lang.String getPlayAuthId() {
    java.lang.Object ref = playAuthId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      playAuthId_ = s;
      return s;
    }
  }
  /**
   * <code>string PlayAuthId = 5;</code>
   * @return The bytes for playAuthId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPlayAuthIdBytes() {
    java.lang.Object ref = playAuthId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      playAuthId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mainPlayUrl_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, mainPlayUrl_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(backupPlayUrl_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, backupPlayUrl_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(abrFormat_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, abrFormat_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(playAuth_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, playAuth_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(playAuthId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, playAuthId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mainPlayUrl_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, mainPlayUrl_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(backupPlayUrl_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, backupPlayUrl_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(abrFormat_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, abrFormat_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(playAuth_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, playAuth_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(playAuthId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, playAuthId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.byteplus.service.vod.model.business.AdaptiveBitrateStreamingInfo)) {
      return super.equals(obj);
    }
    com.byteplus.service.vod.model.business.AdaptiveBitrateStreamingInfo other = (com.byteplus.service.vod.model.business.AdaptiveBitrateStreamingInfo) obj;

    if (!getMainPlayUrl()
        .equals(other.getMainPlayUrl())) return false;
    if (!getBackupPlayUrl()
        .equals(other.getBackupPlayUrl())) return false;
    if (!getAbrFormat()
        .equals(other.getAbrFormat())) return false;
    if (!getPlayAuth()
        .equals(other.getPlayAuth())) return false;
    if (!getPlayAuthId()
        .equals(other.getPlayAuthId())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MAINPLAYURL_FIELD_NUMBER;
    hash = (53 * hash) + getMainPlayUrl().hashCode();
    hash = (37 * hash) + BACKUPPLAYURL_FIELD_NUMBER;
    hash = (53 * hash) + getBackupPlayUrl().hashCode();
    hash = (37 * hash) + ABRFORMAT_FIELD_NUMBER;
    hash = (53 * hash) + getAbrFormat().hashCode();
    hash = (37 * hash) + PLAYAUTH_FIELD_NUMBER;
    hash = (53 * hash) + getPlayAuth().hashCode();
    hash = (37 * hash) + PLAYAUTHID_FIELD_NUMBER;
    hash = (53 * hash) + getPlayAuthId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.byteplus.service.vod.model.business.AdaptiveBitrateStreamingInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.byteplus.service.vod.model.business.AdaptiveBitrateStreamingInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.byteplus.service.vod.model.business.AdaptiveBitrateStreamingInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.byteplus.service.vod.model.business.AdaptiveBitrateStreamingInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.byteplus.service.vod.model.business.AdaptiveBitrateStreamingInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.byteplus.service.vod.model.business.AdaptiveBitrateStreamingInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.byteplus.service.vod.model.business.AdaptiveBitrateStreamingInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.byteplus.service.vod.model.business.AdaptiveBitrateStreamingInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.byteplus.service.vod.model.business.AdaptiveBitrateStreamingInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.byteplus.service.vod.model.business.AdaptiveBitrateStreamingInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.byteplus.service.vod.model.business.AdaptiveBitrateStreamingInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.byteplus.service.vod.model.business.AdaptiveBitrateStreamingInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.byteplus.service.vod.model.business.AdaptiveBitrateStreamingInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Byteplus.Vod.Models.Business.AdaptiveBitrateStreamingInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Byteplus.Vod.Models.Business.AdaptiveBitrateStreamingInfo)
      com.byteplus.service.vod.model.business.AdaptiveBitrateStreamingInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.byteplus.service.vod.model.business.VodCommon.internal_static_Byteplus_Vod_Models_Business_AdaptiveBitrateStreamingInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.byteplus.service.vod.model.business.VodCommon.internal_static_Byteplus_Vod_Models_Business_AdaptiveBitrateStreamingInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.byteplus.service.vod.model.business.AdaptiveBitrateStreamingInfo.class, com.byteplus.service.vod.model.business.AdaptiveBitrateStreamingInfo.Builder.class);
    }

    // Construct using com.byteplus.service.vod.model.business.AdaptiveBitrateStreamingInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      mainPlayUrl_ = "";

      backupPlayUrl_ = "";

      abrFormat_ = "";

      playAuth_ = "";

      playAuthId_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.byteplus.service.vod.model.business.VodCommon.internal_static_Byteplus_Vod_Models_Business_AdaptiveBitrateStreamingInfo_descriptor;
    }

    @java.lang.Override
    public com.byteplus.service.vod.model.business.AdaptiveBitrateStreamingInfo getDefaultInstanceForType() {
      return com.byteplus.service.vod.model.business.AdaptiveBitrateStreamingInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.byteplus.service.vod.model.business.AdaptiveBitrateStreamingInfo build() {
      com.byteplus.service.vod.model.business.AdaptiveBitrateStreamingInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.byteplus.service.vod.model.business.AdaptiveBitrateStreamingInfo buildPartial() {
      com.byteplus.service.vod.model.business.AdaptiveBitrateStreamingInfo result = new com.byteplus.service.vod.model.business.AdaptiveBitrateStreamingInfo(this);
      result.mainPlayUrl_ = mainPlayUrl_;
      result.backupPlayUrl_ = backupPlayUrl_;
      result.abrFormat_ = abrFormat_;
      result.playAuth_ = playAuth_;
      result.playAuthId_ = playAuthId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.byteplus.service.vod.model.business.AdaptiveBitrateStreamingInfo) {
        return mergeFrom((com.byteplus.service.vod.model.business.AdaptiveBitrateStreamingInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.byteplus.service.vod.model.business.AdaptiveBitrateStreamingInfo other) {
      if (other == com.byteplus.service.vod.model.business.AdaptiveBitrateStreamingInfo.getDefaultInstance()) return this;
      if (!other.getMainPlayUrl().isEmpty()) {
        mainPlayUrl_ = other.mainPlayUrl_;
        onChanged();
      }
      if (!other.getBackupPlayUrl().isEmpty()) {
        backupPlayUrl_ = other.backupPlayUrl_;
        onChanged();
      }
      if (!other.getAbrFormat().isEmpty()) {
        abrFormat_ = other.abrFormat_;
        onChanged();
      }
      if (!other.getPlayAuth().isEmpty()) {
        playAuth_ = other.playAuth_;
        onChanged();
      }
      if (!other.getPlayAuthId().isEmpty()) {
        playAuthId_ = other.playAuthId_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.byteplus.service.vod.model.business.AdaptiveBitrateStreamingInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.byteplus.service.vod.model.business.AdaptiveBitrateStreamingInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object mainPlayUrl_ = "";
    /**
     * <pre>
     *主文件主播放地址
     *下发Abr hls时，为主文件主播放地址
     *下发Abr Dash时，为空字符串
     *没有别的场景
     * </pre>
     *
     * <code>string MainPlayUrl = 1;</code>
     * @return The mainPlayUrl.
     */
    public java.lang.String getMainPlayUrl() {
      java.lang.Object ref = mainPlayUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mainPlayUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *主文件主播放地址
     *下发Abr hls时，为主文件主播放地址
     *下发Abr Dash时，为空字符串
     *没有别的场景
     * </pre>
     *
     * <code>string MainPlayUrl = 1;</code>
     * @return The bytes for mainPlayUrl.
     */
    public com.google.protobuf.ByteString
        getMainPlayUrlBytes() {
      java.lang.Object ref = mainPlayUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mainPlayUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *主文件主播放地址
     *下发Abr hls时，为主文件主播放地址
     *下发Abr Dash时，为空字符串
     *没有别的场景
     * </pre>
     *
     * <code>string MainPlayUrl = 1;</code>
     * @param value The mainPlayUrl to set.
     * @return This builder for chaining.
     */
    public Builder setMainPlayUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mainPlayUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *主文件主播放地址
     *下发Abr hls时，为主文件主播放地址
     *下发Abr Dash时，为空字符串
     *没有别的场景
     * </pre>
     *
     * <code>string MainPlayUrl = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMainPlayUrl() {
      
      mainPlayUrl_ = getDefaultInstance().getMainPlayUrl();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *主文件主播放地址
     *下发Abr hls时，为主文件主播放地址
     *下发Abr Dash时，为空字符串
     *没有别的场景
     * </pre>
     *
     * <code>string MainPlayUrl = 1;</code>
     * @param value The bytes for mainPlayUrl to set.
     * @return This builder for chaining.
     */
    public Builder setMainPlayUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mainPlayUrl_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object backupPlayUrl_ = "";
    /**
     * <pre>
     *主文件备播放地址
     *下发Abr hls时，为主文件备播放地址
     *下发Abr Dash时，为空字符串
     *没有别的场景
     * </pre>
     *
     * <code>string BackupPlayUrl = 2;</code>
     * @return The backupPlayUrl.
     */
    public java.lang.String getBackupPlayUrl() {
      java.lang.Object ref = backupPlayUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        backupPlayUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *主文件备播放地址
     *下发Abr hls时，为主文件备播放地址
     *下发Abr Dash时，为空字符串
     *没有别的场景
     * </pre>
     *
     * <code>string BackupPlayUrl = 2;</code>
     * @return The bytes for backupPlayUrl.
     */
    public com.google.protobuf.ByteString
        getBackupPlayUrlBytes() {
      java.lang.Object ref = backupPlayUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        backupPlayUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *主文件备播放地址
     *下发Abr hls时，为主文件备播放地址
     *下发Abr Dash时，为空字符串
     *没有别的场景
     * </pre>
     *
     * <code>string BackupPlayUrl = 2;</code>
     * @param value The backupPlayUrl to set.
     * @return This builder for chaining.
     */
    public Builder setBackupPlayUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      backupPlayUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *主文件备播放地址
     *下发Abr hls时，为主文件备播放地址
     *下发Abr Dash时，为空字符串
     *没有别的场景
     * </pre>
     *
     * <code>string BackupPlayUrl = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearBackupPlayUrl() {
      
      backupPlayUrl_ = getDefaultInstance().getBackupPlayUrl();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *主文件备播放地址
     *下发Abr hls时，为主文件备播放地址
     *下发Abr Dash时，为空字符串
     *没有别的场景
     * </pre>
     *
     * <code>string BackupPlayUrl = 2;</code>
     * @param value The bytes for backupPlayUrl to set.
     * @return This builder for chaining.
     */
    public Builder setBackupPlayUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      backupPlayUrl_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object abrFormat_ = "";
    /**
     * <pre>
     *标识本次下发的ABR码流Format
     *下发Abr hls时，AbrFormat=hls
     *下发Abr Dash时，AbrFormat=dash
     *没有别的场景
     * </pre>
     *
     * <code>string AbrFormat = 3;</code>
     * @return The abrFormat.
     */
    public java.lang.String getAbrFormat() {
      java.lang.Object ref = abrFormat_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        abrFormat_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *标识本次下发的ABR码流Format
     *下发Abr hls时，AbrFormat=hls
     *下发Abr Dash时，AbrFormat=dash
     *没有别的场景
     * </pre>
     *
     * <code>string AbrFormat = 3;</code>
     * @return The bytes for abrFormat.
     */
    public com.google.protobuf.ByteString
        getAbrFormatBytes() {
      java.lang.Object ref = abrFormat_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        abrFormat_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *标识本次下发的ABR码流Format
     *下发Abr hls时，AbrFormat=hls
     *下发Abr Dash时，AbrFormat=dash
     *没有别的场景
     * </pre>
     *
     * <code>string AbrFormat = 3;</code>
     * @param value The abrFormat to set.
     * @return This builder for chaining.
     */
    public Builder setAbrFormat(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      abrFormat_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *标识本次下发的ABR码流Format
     *下发Abr hls时，AbrFormat=hls
     *下发Abr Dash时，AbrFormat=dash
     *没有别的场景
     * </pre>
     *
     * <code>string AbrFormat = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAbrFormat() {
      
      abrFormat_ = getDefaultInstance().getAbrFormat();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *标识本次下发的ABR码流Format
     *下发Abr hls时，AbrFormat=hls
     *下发Abr Dash时，AbrFormat=dash
     *没有别的场景
     * </pre>
     *
     * <code>string AbrFormat = 3;</code>
     * @param value The bytes for abrFormat to set.
     * @return This builder for chaining.
     */
    public Builder setAbrFormatBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      abrFormat_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object playAuth_ = "";
    /**
     * <code>string PlayAuth = 4;</code>
     * @return The playAuth.
     */
    public java.lang.String getPlayAuth() {
      java.lang.Object ref = playAuth_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        playAuth_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string PlayAuth = 4;</code>
     * @return The bytes for playAuth.
     */
    public com.google.protobuf.ByteString
        getPlayAuthBytes() {
      java.lang.Object ref = playAuth_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        playAuth_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string PlayAuth = 4;</code>
     * @param value The playAuth to set.
     * @return This builder for chaining.
     */
    public Builder setPlayAuth(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      playAuth_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string PlayAuth = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlayAuth() {
      
      playAuth_ = getDefaultInstance().getPlayAuth();
      onChanged();
      return this;
    }
    /**
     * <code>string PlayAuth = 4;</code>
     * @param value The bytes for playAuth to set.
     * @return This builder for chaining.
     */
    public Builder setPlayAuthBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      playAuth_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object playAuthId_ = "";
    /**
     * <code>string PlayAuthId = 5;</code>
     * @return The playAuthId.
     */
    public java.lang.String getPlayAuthId() {
      java.lang.Object ref = playAuthId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        playAuthId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string PlayAuthId = 5;</code>
     * @return The bytes for playAuthId.
     */
    public com.google.protobuf.ByteString
        getPlayAuthIdBytes() {
      java.lang.Object ref = playAuthId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        playAuthId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string PlayAuthId = 5;</code>
     * @param value The playAuthId to set.
     * @return This builder for chaining.
     */
    public Builder setPlayAuthId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      playAuthId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string PlayAuthId = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlayAuthId() {
      
      playAuthId_ = getDefaultInstance().getPlayAuthId();
      onChanged();
      return this;
    }
    /**
     * <code>string PlayAuthId = 5;</code>
     * @param value The bytes for playAuthId to set.
     * @return This builder for chaining.
     */
    public Builder setPlayAuthIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      playAuthId_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Byteplus.Vod.Models.Business.AdaptiveBitrateStreamingInfo)
  }

  // @@protoc_insertion_point(class_scope:Byteplus.Vod.Models.Business.AdaptiveBitrateStreamingInfo)
  private static final com.byteplus.service.vod.model.business.AdaptiveBitrateStreamingInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.byteplus.service.vod.model.business.AdaptiveBitrateStreamingInfo();
  }

  public static com.byteplus.service.vod.model.business.AdaptiveBitrateStreamingInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AdaptiveBitrateStreamingInfo>
      PARSER = new com.google.protobuf.AbstractParser<AdaptiveBitrateStreamingInfo>() {
    @java.lang.Override
    public AdaptiveBitrateStreamingInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AdaptiveBitrateStreamingInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AdaptiveBitrateStreamingInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AdaptiveBitrateStreamingInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.byteplus.service.vod.model.business.AdaptiveBitrateStreamingInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

