// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: byteplus/vod/business/vod_quality_platform.proto

package com.byteplus.service.vod.model.business;

public interface GetVodMediaPlayDataColumnOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Byteplus.Vod.Models.Business.GetVodMediaPlayDataColumn)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 字段名
   * </pre>
   *
   * <code>string Name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * 字段名
   * </pre>
   *
   * <code>string Name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * 别名
   * </pre>
   *
   * <code>string Alias = 2;</code>
   * @return The alias.
   */
  java.lang.String getAlias();
  /**
   * <pre>
   * 别名
   * </pre>
   *
   * <code>string Alias = 2;</code>
   * @return The bytes for alias.
   */
  com.google.protobuf.ByteString
      getAliasBytes();

  /**
   * <pre>
   * 类型
   * </pre>
   *
   * <code>string Type = 3;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <pre>
   * 类型
   * </pre>
   *
   * <code>string Type = 3;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <pre>
   * 维度值别名
   * </pre>
   *
   * <code>string ValueAlias = 4;</code>
   * @return The valueAlias.
   */
  java.lang.String getValueAlias();
  /**
   * <pre>
   * 维度值别名
   * </pre>
   *
   * <code>string ValueAlias = 4;</code>
   * @return The bytes for valueAlias.
   */
  com.google.protobuf.ByteString
      getValueAliasBytes();
}
