// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: byteplus/vod/business/vod_common.proto

package com.byteplus.service.vod.model.business;

public interface MirrorSrcConditionOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Byteplus.Vod.Models.Business.MirrorSrcCondition)
        com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int64 HttpCode = 1;</code>
   * @return A list containing the httpCode.
   */
  java.util.List<java.lang.Long> getHttpCodeList();
  /**
   * <code>repeated int64 HttpCode = 1;</code>
   * @return The count of httpCode.
   */
  int getHttpCodeCount();
  /**
   * <code>repeated int64 HttpCode = 1;</code>
   * @param index The index of the element to return.
   * @return The httpCode at the given index.
   */
  long getHttpCode(int index);

  /**
   * <code>.google.protobuf.StringValue KeyPrefix = 2;</code>
   * @return Whether the keyPrefix field is set.
   */
  boolean hasKeyPrefix();
  /**
   * <code>.google.protobuf.StringValue KeyPrefix = 2;</code>
   * @return The keyPrefix.
   */
  com.google.protobuf.StringValue getKeyPrefix();
  /**
   * <code>.google.protobuf.StringValue KeyPrefix = 2;</code>
   */
  com.google.protobuf.StringValueOrBuilder getKeyPrefixOrBuilder();

  /**
   * <code>.google.protobuf.StringValue KeySuffix = 3;</code>
   * @return Whether the keySuffix field is set.
   */
  boolean hasKeySuffix();
  /**
   * <code>.google.protobuf.StringValue KeySuffix = 3;</code>
   * @return The keySuffix.
   */
  com.google.protobuf.StringValue getKeySuffix();
  /**
   * <code>.google.protobuf.StringValue KeySuffix = 3;</code>
   */
  com.google.protobuf.StringValueOrBuilder getKeySuffixOrBuilder();

  /**
   * <code>repeated string AllowHost = 4;</code>
   * @return A list containing the allowHost.
   */
  java.util.List<java.lang.String>
  getAllowHostList();
  /**
   * <code>repeated string AllowHost = 4;</code>
   * @return The count of allowHost.
   */
  int getAllowHostCount();
  /**
   * <code>repeated string AllowHost = 4;</code>
   * @param index The index of the element to return.
   * @return The allowHost at the given index.
   */
  java.lang.String getAllowHost(int index);
  /**
   * <code>repeated string AllowHost = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the allowHost at the given index.
   */
  com.google.protobuf.ByteString
  getAllowHostBytes(int index);
}
