// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: byteplus/vod/business/vod_cdn.proto

package com.byteplus.service.vod.model.business;

public interface OriginLineOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Byteplus.Vod.Models.Business.OriginLine)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 源站地址
   * </pre>
   *
   * <code>string Address = 1;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <pre>
   * 源站地址
   * </pre>
   *
   * <code>string Address = 1;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <pre>
   * 下面两个参数由于目前 BP 没有用到，所以先注释掉
   *  string HttpPort = 2;      // HTTP协议端口
   *  string HttpsPort = 3;     // HTTPS协议端口
   * </pre>
   *
   * <code>string InstanceType = 4;</code>
   * @return The instanceType.
   */
  java.lang.String getInstanceType();
  /**
   * <pre>
   * 下面两个参数由于目前 BP 没有用到，所以先注释掉
   *  string HttpPort = 2;      // HTTP协议端口
   *  string HttpsPort = 3;     // HTTPS协议端口
   * </pre>
   *
   * <code>string InstanceType = 4;</code>
   * @return The bytes for instanceType.
   */
  com.google.protobuf.ByteString
      getInstanceTypeBytes();

  /**
   * <pre>
   * 回源请求访问的站点域名
   * </pre>
   *
   * <code>string OriginHost = 5;</code>
   * @return The originHost.
   */
  java.lang.String getOriginHost();
  /**
   * <pre>
   * 回源请求访问的站点域名
   * </pre>
   *
   * <code>string OriginHost = 5;</code>
   * @return The bytes for originHost.
   */
  com.google.protobuf.ByteString
      getOriginHostBytes();
}
