// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: byteplus/vod/business/vod_workflow.proto

package com.byteplus.service.vod.model.business;

public interface OverrideParamsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Byteplus.Vod.Models.Business.OverrideParams)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 水印覆盖参数
   * </pre>
   *
   * <code>repeated .Byteplus.Vod.Models.Business.LogoOverride Logo = 1;</code>
   */
  java.util.List<com.byteplus.service.vod.model.business.LogoOverride> 
      getLogoList();
  /**
   * <pre>
   * 水印覆盖参数
   * </pre>
   *
   * <code>repeated .Byteplus.Vod.Models.Business.LogoOverride Logo = 1;</code>
   */
  com.byteplus.service.vod.model.business.LogoOverride getLogo(int index);
  /**
   * <pre>
   * 水印覆盖参数
   * </pre>
   *
   * <code>repeated .Byteplus.Vod.Models.Business.LogoOverride Logo = 1;</code>
   */
  int getLogoCount();
  /**
   * <pre>
   * 水印覆盖参数
   * </pre>
   *
   * <code>repeated .Byteplus.Vod.Models.Business.LogoOverride Logo = 1;</code>
   */
  java.util.List<? extends com.byteplus.service.vod.model.business.LogoOverrideOrBuilder> 
      getLogoOrBuilderList();
  /**
   * <pre>
   * 水印覆盖参数
   * </pre>
   *
   * <code>repeated .Byteplus.Vod.Models.Business.LogoOverride Logo = 1;</code>
   */
  com.byteplus.service.vod.model.business.LogoOverrideOrBuilder getLogoOrBuilder(
      int index);

  /**
   * <pre>
   * 视频转码覆盖参数
   * </pre>
   *
   * <code>repeated .Byteplus.Vod.Models.Business.TranscodeVideoOverride TranscodeVideo = 2;</code>
   */
  java.util.List<com.byteplus.service.vod.model.business.TranscodeVideoOverride> 
      getTranscodeVideoList();
  /**
   * <pre>
   * 视频转码覆盖参数
   * </pre>
   *
   * <code>repeated .Byteplus.Vod.Models.Business.TranscodeVideoOverride TranscodeVideo = 2;</code>
   */
  com.byteplus.service.vod.model.business.TranscodeVideoOverride getTranscodeVideo(int index);
  /**
   * <pre>
   * 视频转码覆盖参数
   * </pre>
   *
   * <code>repeated .Byteplus.Vod.Models.Business.TranscodeVideoOverride TranscodeVideo = 2;</code>
   */
  int getTranscodeVideoCount();
  /**
   * <pre>
   * 视频转码覆盖参数
   * </pre>
   *
   * <code>repeated .Byteplus.Vod.Models.Business.TranscodeVideoOverride TranscodeVideo = 2;</code>
   */
  java.util.List<? extends com.byteplus.service.vod.model.business.TranscodeVideoOverrideOrBuilder> 
      getTranscodeVideoOrBuilderList();
  /**
   * <pre>
   * 视频转码覆盖参数
   * </pre>
   *
   * <code>repeated .Byteplus.Vod.Models.Business.TranscodeVideoOverride TranscodeVideo = 2;</code>
   */
  com.byteplus.service.vod.model.business.TranscodeVideoOverrideOrBuilder getTranscodeVideoOrBuilder(
      int index);

  /**
   * <pre>
   * 音频转码覆盖参数
   * </pre>
   *
   * <code>repeated .Byteplus.Vod.Models.Business.TranscodeAudioOverride TranscodeAudio = 3;</code>
   */
  java.util.List<com.byteplus.service.vod.model.business.TranscodeAudioOverride> 
      getTranscodeAudioList();
  /**
   * <pre>
   * 音频转码覆盖参数
   * </pre>
   *
   * <code>repeated .Byteplus.Vod.Models.Business.TranscodeAudioOverride TranscodeAudio = 3;</code>
   */
  com.byteplus.service.vod.model.business.TranscodeAudioOverride getTranscodeAudio(int index);
  /**
   * <pre>
   * 音频转码覆盖参数
   * </pre>
   *
   * <code>repeated .Byteplus.Vod.Models.Business.TranscodeAudioOverride TranscodeAudio = 3;</code>
   */
  int getTranscodeAudioCount();
  /**
   * <pre>
   * 音频转码覆盖参数
   * </pre>
   *
   * <code>repeated .Byteplus.Vod.Models.Business.TranscodeAudioOverride TranscodeAudio = 3;</code>
   */
  java.util.List<? extends com.byteplus.service.vod.model.business.TranscodeAudioOverrideOrBuilder> 
      getTranscodeAudioOrBuilderList();
  /**
   * <pre>
   * 音频转码覆盖参数
   * </pre>
   *
   * <code>repeated .Byteplus.Vod.Models.Business.TranscodeAudioOverride TranscodeAudio = 3;</code>
   */
  com.byteplus.service.vod.model.business.TranscodeAudioOverrideOrBuilder getTranscodeAudioOrBuilder(
      int index);

  /**
   * <pre>
   * 截图覆盖参数
   * </pre>
   *
   * <code>repeated .Byteplus.Vod.Models.Business.SnapshotOverride Snapshot = 4;</code>
   */
  java.util.List<com.byteplus.service.vod.model.business.SnapshotOverride> 
      getSnapshotList();
  /**
   * <pre>
   * 截图覆盖参数
   * </pre>
   *
   * <code>repeated .Byteplus.Vod.Models.Business.SnapshotOverride Snapshot = 4;</code>
   */
  com.byteplus.service.vod.model.business.SnapshotOverride getSnapshot(int index);
  /**
   * <pre>
   * 截图覆盖参数
   * </pre>
   *
   * <code>repeated .Byteplus.Vod.Models.Business.SnapshotOverride Snapshot = 4;</code>
   */
  int getSnapshotCount();
  /**
   * <pre>
   * 截图覆盖参数
   * </pre>
   *
   * <code>repeated .Byteplus.Vod.Models.Business.SnapshotOverride Snapshot = 4;</code>
   */
  java.util.List<? extends com.byteplus.service.vod.model.business.SnapshotOverrideOrBuilder> 
      getSnapshotOrBuilderList();
  /**
   * <pre>
   * 截图覆盖参数
   * </pre>
   *
   * <code>repeated .Byteplus.Vod.Models.Business.SnapshotOverride Snapshot = 4;</code>
   */
  com.byteplus.service.vod.model.business.SnapshotOverrideOrBuilder getSnapshotOrBuilder(
      int index);

  /**
   * <pre>
   * 增强覆盖参数
   * </pre>
   *
   * <code>.Byteplus.Vod.Models.Business.EnhanceOverride Enhance = 5;</code>
   * @return Whether the enhance field is set.
   */
  boolean hasEnhance();
  /**
   * <pre>
   * 增强覆盖参数
   * </pre>
   *
   * <code>.Byteplus.Vod.Models.Business.EnhanceOverride Enhance = 5;</code>
   * @return The enhance.
   */
  com.byteplus.service.vod.model.business.EnhanceOverride getEnhance();
  /**
   * <pre>
   * 增强覆盖参数
   * </pre>
   *
   * <code>.Byteplus.Vod.Models.Business.EnhanceOverride Enhance = 5;</code>
   */
  com.byteplus.service.vod.model.business.EnhanceOverrideOrBuilder getEnhanceOrBuilder();
}
