// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: byteplus/vod/business/vod_common.proto

package com.byteplus.service.vod.model.business;

/**
 * Protobuf type {@code Byteplus.Vod.Models.Business.PublicSourceConf}
 */
public final class PublicSourceConf extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Byteplus.Vod.Models.Business.PublicSourceConf)
    PublicSourceConfOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PublicSourceConf.newBuilder() to construct.
  private PublicSourceConf(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PublicSourceConf() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PublicSourceConf();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PublicSourceConf(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.byteplus.service.vod.model.business.MirrorSrcS3Conf.Builder subBuilder = null;
            if (s3_ != null) {
              subBuilder = s3_.toBuilder();
            }
            s3_ = input.readMessage(com.byteplus.service.vod.model.business.MirrorSrcS3Conf.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(s3_);
              s3_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.byteplus.service.vod.model.business.VodCommon.internal_static_Byteplus_Vod_Models_Business_PublicSourceConf_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.byteplus.service.vod.model.business.VodCommon.internal_static_Byteplus_Vod_Models_Business_PublicSourceConf_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.byteplus.service.vod.model.business.PublicSourceConf.class, com.byteplus.service.vod.model.business.PublicSourceConf.Builder.class);
  }

  public static final int S3_FIELD_NUMBER = 1;
  private com.byteplus.service.vod.model.business.MirrorSrcS3Conf s3_;
  /**
   * <code>.Byteplus.Vod.Models.Business.MirrorSrcS3Conf S3 = 1;</code>
   * @return Whether the s3 field is set.
   */
  @java.lang.Override
  public boolean hasS3() {
    return s3_ != null;
  }
  /**
   * <code>.Byteplus.Vod.Models.Business.MirrorSrcS3Conf S3 = 1;</code>
   * @return The s3.
   */
  @java.lang.Override
  public com.byteplus.service.vod.model.business.MirrorSrcS3Conf getS3() {
    return s3_ == null ? com.byteplus.service.vod.model.business.MirrorSrcS3Conf.getDefaultInstance() : s3_;
  }
  /**
   * <code>.Byteplus.Vod.Models.Business.MirrorSrcS3Conf S3 = 1;</code>
   */
  @java.lang.Override
  public com.byteplus.service.vod.model.business.MirrorSrcS3ConfOrBuilder getS3OrBuilder() {
    return getS3();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (s3_ != null) {
      output.writeMessage(1, getS3());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (s3_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getS3());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.byteplus.service.vod.model.business.PublicSourceConf)) {
      return super.equals(obj);
    }
    com.byteplus.service.vod.model.business.PublicSourceConf other = (com.byteplus.service.vod.model.business.PublicSourceConf) obj;

    if (hasS3() != other.hasS3()) return false;
    if (hasS3()) {
      if (!getS3()
          .equals(other.getS3())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasS3()) {
      hash = (37 * hash) + S3_FIELD_NUMBER;
      hash = (53 * hash) + getS3().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.byteplus.service.vod.model.business.PublicSourceConf parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.byteplus.service.vod.model.business.PublicSourceConf parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.byteplus.service.vod.model.business.PublicSourceConf parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.byteplus.service.vod.model.business.PublicSourceConf parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.byteplus.service.vod.model.business.PublicSourceConf parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.byteplus.service.vod.model.business.PublicSourceConf parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.byteplus.service.vod.model.business.PublicSourceConf parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.byteplus.service.vod.model.business.PublicSourceConf parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.byteplus.service.vod.model.business.PublicSourceConf parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.byteplus.service.vod.model.business.PublicSourceConf parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.byteplus.service.vod.model.business.PublicSourceConf parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.byteplus.service.vod.model.business.PublicSourceConf parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.byteplus.service.vod.model.business.PublicSourceConf prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Byteplus.Vod.Models.Business.PublicSourceConf}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Byteplus.Vod.Models.Business.PublicSourceConf)
      com.byteplus.service.vod.model.business.PublicSourceConfOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.byteplus.service.vod.model.business.VodCommon.internal_static_Byteplus_Vod_Models_Business_PublicSourceConf_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.byteplus.service.vod.model.business.VodCommon.internal_static_Byteplus_Vod_Models_Business_PublicSourceConf_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.byteplus.service.vod.model.business.PublicSourceConf.class, com.byteplus.service.vod.model.business.PublicSourceConf.Builder.class);
    }

    // Construct using com.byteplus.service.vod.model.business.PublicSourceConf.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (s3Builder_ == null) {
        s3_ = null;
      } else {
        s3_ = null;
        s3Builder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.byteplus.service.vod.model.business.VodCommon.internal_static_Byteplus_Vod_Models_Business_PublicSourceConf_descriptor;
    }

    @java.lang.Override
    public com.byteplus.service.vod.model.business.PublicSourceConf getDefaultInstanceForType() {
      return com.byteplus.service.vod.model.business.PublicSourceConf.getDefaultInstance();
    }

    @java.lang.Override
    public com.byteplus.service.vod.model.business.PublicSourceConf build() {
      com.byteplus.service.vod.model.business.PublicSourceConf result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.byteplus.service.vod.model.business.PublicSourceConf buildPartial() {
      com.byteplus.service.vod.model.business.PublicSourceConf result = new com.byteplus.service.vod.model.business.PublicSourceConf(this);
      if (s3Builder_ == null) {
        result.s3_ = s3_;
      } else {
        result.s3_ = s3Builder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.byteplus.service.vod.model.business.PublicSourceConf) {
        return mergeFrom((com.byteplus.service.vod.model.business.PublicSourceConf)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.byteplus.service.vod.model.business.PublicSourceConf other) {
      if (other == com.byteplus.service.vod.model.business.PublicSourceConf.getDefaultInstance()) return this;
      if (other.hasS3()) {
        mergeS3(other.getS3());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.byteplus.service.vod.model.business.PublicSourceConf parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.byteplus.service.vod.model.business.PublicSourceConf) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.byteplus.service.vod.model.business.MirrorSrcS3Conf s3_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.byteplus.service.vod.model.business.MirrorSrcS3Conf, com.byteplus.service.vod.model.business.MirrorSrcS3Conf.Builder, com.byteplus.service.vod.model.business.MirrorSrcS3ConfOrBuilder> s3Builder_;
    /**
     * <code>.Byteplus.Vod.Models.Business.MirrorSrcS3Conf S3 = 1;</code>
     * @return Whether the s3 field is set.
     */
    public boolean hasS3() {
      return s3Builder_ != null || s3_ != null;
    }
    /**
     * <code>.Byteplus.Vod.Models.Business.MirrorSrcS3Conf S3 = 1;</code>
     * @return The s3.
     */
    public com.byteplus.service.vod.model.business.MirrorSrcS3Conf getS3() {
      if (s3Builder_ == null) {
        return s3_ == null ? com.byteplus.service.vod.model.business.MirrorSrcS3Conf.getDefaultInstance() : s3_;
      } else {
        return s3Builder_.getMessage();
      }
    }
    /**
     * <code>.Byteplus.Vod.Models.Business.MirrorSrcS3Conf S3 = 1;</code>
     */
    public Builder setS3(com.byteplus.service.vod.model.business.MirrorSrcS3Conf value) {
      if (s3Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        s3_ = value;
        onChanged();
      } else {
        s3Builder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Byteplus.Vod.Models.Business.MirrorSrcS3Conf S3 = 1;</code>
     */
    public Builder setS3(
        com.byteplus.service.vod.model.business.MirrorSrcS3Conf.Builder builderForValue) {
      if (s3Builder_ == null) {
        s3_ = builderForValue.build();
        onChanged();
      } else {
        s3Builder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Byteplus.Vod.Models.Business.MirrorSrcS3Conf S3 = 1;</code>
     */
    public Builder mergeS3(com.byteplus.service.vod.model.business.MirrorSrcS3Conf value) {
      if (s3Builder_ == null) {
        if (s3_ != null) {
          s3_ =
            com.byteplus.service.vod.model.business.MirrorSrcS3Conf.newBuilder(s3_).mergeFrom(value).buildPartial();
        } else {
          s3_ = value;
        }
        onChanged();
      } else {
        s3Builder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Byteplus.Vod.Models.Business.MirrorSrcS3Conf S3 = 1;</code>
     */
    public Builder clearS3() {
      if (s3Builder_ == null) {
        s3_ = null;
        onChanged();
      } else {
        s3_ = null;
        s3Builder_ = null;
      }

      return this;
    }
    /**
     * <code>.Byteplus.Vod.Models.Business.MirrorSrcS3Conf S3 = 1;</code>
     */
    public com.byteplus.service.vod.model.business.MirrorSrcS3Conf.Builder getS3Builder() {
      
      onChanged();
      return getS3FieldBuilder().getBuilder();
    }
    /**
     * <code>.Byteplus.Vod.Models.Business.MirrorSrcS3Conf S3 = 1;</code>
     */
    public com.byteplus.service.vod.model.business.MirrorSrcS3ConfOrBuilder getS3OrBuilder() {
      if (s3Builder_ != null) {
        return s3Builder_.getMessageOrBuilder();
      } else {
        return s3_ == null ?
            com.byteplus.service.vod.model.business.MirrorSrcS3Conf.getDefaultInstance() : s3_;
      }
    }
    /**
     * <code>.Byteplus.Vod.Models.Business.MirrorSrcS3Conf S3 = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.byteplus.service.vod.model.business.MirrorSrcS3Conf, com.byteplus.service.vod.model.business.MirrorSrcS3Conf.Builder, com.byteplus.service.vod.model.business.MirrorSrcS3ConfOrBuilder> 
        getS3FieldBuilder() {
      if (s3Builder_ == null) {
        s3Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.byteplus.service.vod.model.business.MirrorSrcS3Conf, com.byteplus.service.vod.model.business.MirrorSrcS3Conf.Builder, com.byteplus.service.vod.model.business.MirrorSrcS3ConfOrBuilder>(
                getS3(),
                getParentForChildren(),
                isClean());
        s3_ = null;
      }
      return s3Builder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Byteplus.Vod.Models.Business.PublicSourceConf)
  }

  // @@protoc_insertion_point(class_scope:Byteplus.Vod.Models.Business.PublicSourceConf)
  private static final com.byteplus.service.vod.model.business.PublicSourceConf DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.byteplus.service.vod.model.business.PublicSourceConf();
  }

  public static com.byteplus.service.vod.model.business.PublicSourceConf getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PublicSourceConf>
      PARSER = new com.google.protobuf.AbstractParser<PublicSourceConf>() {
    @java.lang.Override
    public PublicSourceConf parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PublicSourceConf(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PublicSourceConf> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PublicSourceConf> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.byteplus.service.vod.model.business.PublicSourceConf getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

