// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: byteplus/vod/business/vod_callback.proto

package com.byteplus.service.vod.model.business;

public final class VodCallback {
  private VodCallback() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(byteplus/vod/business/vod_callback.pro" +
      "to\022\034Byteplus.Vod.Models.Business*V\n\023VodC" +
      "allbackAuthType\022\037\n\033VodCallbackAuthTypeDi" +
      "sabled\020\000\022\036\n\032VodCallbackAuthTypeEnabled\020\001" +
      "B\333\001\n\'com.byteplus.service.vod.model.busi" +
      "nessB\013VodCallbackP\001ZGgithub.com/byteplus" +
      "-sdk/byteplus-sdk-golang/service/vod/mod" +
      "els/business\240\001\001\330\001\001\302\002\000\312\002$Byteplus\\Service" +
      "\\Vod\\Models\\Business\342\002\'Byteplus\\Service\\" +
      "Vod\\Models\\GPBMetadatab\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
