// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: byteplus/vod/business/vod_cdn.proto

package com.byteplus.service.vod.model.business;

public interface VodDomainInstanceInfosOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Byteplus.Vod.Models.Business.VodDomainInstanceInfos)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 点播源站实例列表
   * </pre>
   *
   * <code>repeated .Byteplus.Vod.Models.Business.VodDomainInstanceInfo ByteInstances = 1;</code>
   */
  java.util.List<com.byteplus.service.vod.model.business.VodDomainInstanceInfo> 
      getByteInstancesList();
  /**
   * <pre>
   * 点播源站实例列表
   * </pre>
   *
   * <code>repeated .Byteplus.Vod.Models.Business.VodDomainInstanceInfo ByteInstances = 1;</code>
   */
  com.byteplus.service.vod.model.business.VodDomainInstanceInfo getByteInstances(int index);
  /**
   * <pre>
   * 点播源站实例列表
   * </pre>
   *
   * <code>repeated .Byteplus.Vod.Models.Business.VodDomainInstanceInfo ByteInstances = 1;</code>
   */
  int getByteInstancesCount();
  /**
   * <pre>
   * 点播源站实例列表
   * </pre>
   *
   * <code>repeated .Byteplus.Vod.Models.Business.VodDomainInstanceInfo ByteInstances = 1;</code>
   */
  java.util.List<? extends com.byteplus.service.vod.model.business.VodDomainInstanceInfoOrBuilder> 
      getByteInstancesOrBuilderList();
  /**
   * <pre>
   * 点播源站实例列表
   * </pre>
   *
   * <code>repeated .Byteplus.Vod.Models.Business.VodDomainInstanceInfo ByteInstances = 1;</code>
   */
  com.byteplus.service.vod.model.business.VodDomainInstanceInfoOrBuilder getByteInstancesOrBuilder(
      int index);

  /**
   * <pre>
   * 第三方源站实力列表
   * </pre>
   *
   * <code>repeated .Byteplus.Vod.Models.Business.VodDomainInstanceInfo OtherInstances = 2;</code>
   */
  java.util.List<com.byteplus.service.vod.model.business.VodDomainInstanceInfo> 
      getOtherInstancesList();
  /**
   * <pre>
   * 第三方源站实力列表
   * </pre>
   *
   * <code>repeated .Byteplus.Vod.Models.Business.VodDomainInstanceInfo OtherInstances = 2;</code>
   */
  com.byteplus.service.vod.model.business.VodDomainInstanceInfo getOtherInstances(int index);
  /**
   * <pre>
   * 第三方源站实力列表
   * </pre>
   *
   * <code>repeated .Byteplus.Vod.Models.Business.VodDomainInstanceInfo OtherInstances = 2;</code>
   */
  int getOtherInstancesCount();
  /**
   * <pre>
   * 第三方源站实力列表
   * </pre>
   *
   * <code>repeated .Byteplus.Vod.Models.Business.VodDomainInstanceInfo OtherInstances = 2;</code>
   */
  java.util.List<? extends com.byteplus.service.vod.model.business.VodDomainInstanceInfoOrBuilder> 
      getOtherInstancesOrBuilderList();
  /**
   * <pre>
   * 第三方源站实力列表
   * </pre>
   *
   * <code>repeated .Byteplus.Vod.Models.Business.VodDomainInstanceInfo OtherInstances = 2;</code>
   */
  com.byteplus.service.vod.model.business.VodDomainInstanceInfoOrBuilder getOtherInstancesOrBuilder(
      int index);
}
