// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: byteplus/vod/business/vod_cdn.proto

package com.byteplus.service.vod.model.business;

public interface VodDomainInstanceInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Byteplus.Vod.Models.Business.VodDomainInstanceInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *实例ID，废弃
   * </pre>
   *
   * <code>string InstanceId = 1;</code>
   * @return The instanceId.
   */
  java.lang.String getInstanceId();
  /**
   * <pre>
   *实例ID，废弃
   * </pre>
   *
   * <code>string InstanceId = 1;</code>
   * @return The bytes for instanceId.
   */
  com.google.protobuf.ByteString
      getInstanceIdBytes();

  /**
   * <pre>
   *域名列表
   * </pre>
   *
   * <code>repeated .Byteplus.Vod.Models.Business.VodDomainoInfo Domains = 2;</code>
   */
  java.util.List<com.byteplus.service.vod.model.business.VodDomainoInfo> 
      getDomainsList();
  /**
   * <pre>
   *域名列表
   * </pre>
   *
   * <code>repeated .Byteplus.Vod.Models.Business.VodDomainoInfo Domains = 2;</code>
   */
  com.byteplus.service.vod.model.business.VodDomainoInfo getDomains(int index);
  /**
   * <pre>
   *域名列表
   * </pre>
   *
   * <code>repeated .Byteplus.Vod.Models.Business.VodDomainoInfo Domains = 2;</code>
   */
  int getDomainsCount();
  /**
   * <pre>
   *域名列表
   * </pre>
   *
   * <code>repeated .Byteplus.Vod.Models.Business.VodDomainoInfo Domains = 2;</code>
   */
  java.util.List<? extends com.byteplus.service.vod.model.business.VodDomainoInfoOrBuilder> 
      getDomainsOrBuilderList();
  /**
   * <pre>
   *域名列表
   * </pre>
   *
   * <code>repeated .Byteplus.Vod.Models.Business.VodDomainoInfo Domains = 2;</code>
   */
  com.byteplus.service.vod.model.business.VodDomainoInfoOrBuilder getDomainsOrBuilder(
      int index);

  /**
   * <pre>
   *是否可自助配置，废弃
   * </pre>
   *
   * <code>bool CanSelfEditing = 3;</code>
   * @return The canSelfEditing.
   */
  boolean getCanSelfEditing();

  /**
   * <pre>
   *实例配置状态，废弃
   * </pre>
   *
   * <code>string ConfigStatus = 4;</code>
   * @return The configStatus.
   */
  java.lang.String getConfigStatus();
  /**
   * <pre>
   *实例配置状态，废弃
   * </pre>
   *
   * <code>string ConfigStatus = 4;</code>
   * @return The bytes for configStatus.
   */
  com.google.protobuf.ByteString
      getConfigStatusBytes();
}
