// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: byteplus/vod/business/vod_media.proto

package com.byteplus.service.vod.model.business;

/**
 * Protobuf type {@code Byteplus.Vod.Models.Business.VodGetPlaylistsResult}
 */
public final class VodGetPlaylistsResult extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:Byteplus.Vod.Models.Business.VodGetPlaylistsResult)
        VodGetPlaylistsResultOrBuilder {
  private static final long serialVersionUID = 0L;
  // Use VodGetPlaylistsResult.newBuilder() to construct.
  private VodGetPlaylistsResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private VodGetPlaylistsResult() {
    playlists_ = java.util.Collections.emptyList();
    invalidPlaylists_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
    return new VodGetPlaylistsResult();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private VodGetPlaylistsResult(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              playlists_ = new java.util.ArrayList<com.byteplus.service.vod.model.business.VodPlaylistInfo>();
              mutable_bitField0_ |= 0x00000001;
            }
            playlists_.add(
                    input.readMessage(com.byteplus.service.vod.model.business.VodPlaylistInfo.parser(), extensionRegistry));
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              invalidPlaylists_ = new java.util.ArrayList<com.byteplus.service.vod.model.business.InvalidPlaylist>();
              mutable_bitField0_ |= 0x00000002;
            }
            invalidPlaylists_.add(
                    input.readMessage(com.byteplus.service.vod.model.business.InvalidPlaylist.parser(), extensionRegistry));
            break;
          }
          case 24: {

            total_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        playlists_ = java.util.Collections.unmodifiableList(playlists_);
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        invalidPlaylists_ = java.util.Collections.unmodifiableList(invalidPlaylists_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
  getDescriptor() {
    return com.byteplus.service.vod.model.business.VodMedia.internal_static_Byteplus_Vod_Models_Business_VodGetPlaylistsResult_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
  internalGetFieldAccessorTable() {
    return com.byteplus.service.vod.model.business.VodMedia.internal_static_Byteplus_Vod_Models_Business_VodGetPlaylistsResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                    com.byteplus.service.vod.model.business.VodGetPlaylistsResult.class, com.byteplus.service.vod.model.business.VodGetPlaylistsResult.Builder.class);
  }

  public static final int PLAYLISTS_FIELD_NUMBER = 1;
  private java.util.List<com.byteplus.service.vod.model.business.VodPlaylistInfo> playlists_;
  /**
   * <code>repeated .Byteplus.Vod.Models.Business.VodPlaylistInfo Playlists = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.byteplus.service.vod.model.business.VodPlaylistInfo> getPlaylistsList() {
    return playlists_;
  }
  /**
   * <code>repeated .Byteplus.Vod.Models.Business.VodPlaylistInfo Playlists = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.byteplus.service.vod.model.business.VodPlaylistInfoOrBuilder>
  getPlaylistsOrBuilderList() {
    return playlists_;
  }
  /**
   * <code>repeated .Byteplus.Vod.Models.Business.VodPlaylistInfo Playlists = 1;</code>
   */
  @java.lang.Override
  public int getPlaylistsCount() {
    return playlists_.size();
  }
  /**
   * <code>repeated .Byteplus.Vod.Models.Business.VodPlaylistInfo Playlists = 1;</code>
   */
  @java.lang.Override
  public com.byteplus.service.vod.model.business.VodPlaylistInfo getPlaylists(int index) {
    return playlists_.get(index);
  }
  /**
   * <code>repeated .Byteplus.Vod.Models.Business.VodPlaylistInfo Playlists = 1;</code>
   */
  @java.lang.Override
  public com.byteplus.service.vod.model.business.VodPlaylistInfoOrBuilder getPlaylistsOrBuilder(
          int index) {
    return playlists_.get(index);
  }

  public static final int INVALIDPLAYLISTS_FIELD_NUMBER = 2;
  private java.util.List<com.byteplus.service.vod.model.business.InvalidPlaylist> invalidPlaylists_;
  /**
   * <code>repeated .Byteplus.Vod.Models.Business.InvalidPlaylist InvalidPlaylists = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.byteplus.service.vod.model.business.InvalidPlaylist> getInvalidPlaylistsList() {
    return invalidPlaylists_;
  }
  /**
   * <code>repeated .Byteplus.Vod.Models.Business.InvalidPlaylist InvalidPlaylists = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.byteplus.service.vod.model.business.InvalidPlaylistOrBuilder>
  getInvalidPlaylistsOrBuilderList() {
    return invalidPlaylists_;
  }
  /**
   * <code>repeated .Byteplus.Vod.Models.Business.InvalidPlaylist InvalidPlaylists = 2;</code>
   */
  @java.lang.Override
  public int getInvalidPlaylistsCount() {
    return invalidPlaylists_.size();
  }
  /**
   * <code>repeated .Byteplus.Vod.Models.Business.InvalidPlaylist InvalidPlaylists = 2;</code>
   */
  @java.lang.Override
  public com.byteplus.service.vod.model.business.InvalidPlaylist getInvalidPlaylists(int index) {
    return invalidPlaylists_.get(index);
  }
  /**
   * <code>repeated .Byteplus.Vod.Models.Business.InvalidPlaylist InvalidPlaylists = 2;</code>
   */
  @java.lang.Override
  public com.byteplus.service.vod.model.business.InvalidPlaylistOrBuilder getInvalidPlaylistsOrBuilder(
          int index) {
    return invalidPlaylists_.get(index);
  }

  public static final int TOTAL_FIELD_NUMBER = 3;
  private int total_;
  /**
   * <code>int32 Total = 3;</code>
   * @return The total.
   */
  @java.lang.Override
  public int getTotal() {
    return total_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
          throws java.io.IOException {
    for (int i = 0; i < playlists_.size(); i++) {
      output.writeMessage(1, playlists_.get(i));
    }
    for (int i = 0; i < invalidPlaylists_.size(); i++) {
      output.writeMessage(2, invalidPlaylists_.get(i));
    }
    if (total_ != 0) {
      output.writeInt32(3, total_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < playlists_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
              .computeMessageSize(1, playlists_.get(i));
    }
    for (int i = 0; i < invalidPlaylists_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
              .computeMessageSize(2, invalidPlaylists_.get(i));
    }
    if (total_ != 0) {
      size += com.google.protobuf.CodedOutputStream
              .computeInt32Size(3, total_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof com.byteplus.service.vod.model.business.VodGetPlaylistsResult)) {
      return super.equals(obj);
    }
    com.byteplus.service.vod.model.business.VodGetPlaylistsResult other = (com.byteplus.service.vod.model.business.VodGetPlaylistsResult) obj;

    if (!getPlaylistsList()
            .equals(other.getPlaylistsList())) return false;
    if (!getInvalidPlaylistsList()
            .equals(other.getInvalidPlaylistsList())) return false;
    if (getTotal()
            != other.getTotal()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getPlaylistsCount() > 0) {
      hash = (37 * hash) + PLAYLISTS_FIELD_NUMBER;
      hash = (53 * hash) + getPlaylistsList().hashCode();
    }
    if (getInvalidPlaylistsCount() > 0) {
      hash = (37 * hash) + INVALIDPLAYLISTS_FIELD_NUMBER;
      hash = (53 * hash) + getInvalidPlaylistsList().hashCode();
    }
    hash = (37 * hash) + TOTAL_FIELD_NUMBER;
    hash = (53 * hash) + getTotal();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.byteplus.service.vod.model.business.VodGetPlaylistsResult parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.byteplus.service.vod.model.business.VodGetPlaylistsResult parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.byteplus.service.vod.model.business.VodGetPlaylistsResult parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.byteplus.service.vod.model.business.VodGetPlaylistsResult parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.byteplus.service.vod.model.business.VodGetPlaylistsResult parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.byteplus.service.vod.model.business.VodGetPlaylistsResult parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.byteplus.service.vod.model.business.VodGetPlaylistsResult parseFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }
  public static com.byteplus.service.vod.model.business.VodGetPlaylistsResult parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.byteplus.service.vod.model.business.VodGetPlaylistsResult parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.byteplus.service.vod.model.business.VodGetPlaylistsResult parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.byteplus.service.vod.model.business.VodGetPlaylistsResult parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }
  public static com.byteplus.service.vod.model.business.VodGetPlaylistsResult parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.byteplus.service.vod.model.business.VodGetPlaylistsResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Byteplus.Vod.Models.Business.VodGetPlaylistsResult}
   */
  public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Byteplus.Vod.Models.Business.VodGetPlaylistsResult)
          com.byteplus.service.vod.model.business.VodGetPlaylistsResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return com.byteplus.service.vod.model.business.VodMedia.internal_static_Byteplus_Vod_Models_Business_VodGetPlaylistsResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return com.byteplus.service.vod.model.business.VodMedia.internal_static_Byteplus_Vod_Models_Business_VodGetPlaylistsResult_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      com.byteplus.service.vod.model.business.VodGetPlaylistsResult.class, com.byteplus.service.vod.model.business.VodGetPlaylistsResult.Builder.class);
    }

    // Construct using com.byteplus.service.vod.model.business.VodGetPlaylistsResult.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPlaylistsFieldBuilder();
        getInvalidPlaylistsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (playlistsBuilder_ == null) {
        playlists_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        playlistsBuilder_.clear();
      }
      if (invalidPlaylistsBuilder_ == null) {
        invalidPlaylists_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        invalidPlaylistsBuilder_.clear();
      }
      total_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
    getDescriptorForType() {
      return com.byteplus.service.vod.model.business.VodMedia.internal_static_Byteplus_Vod_Models_Business_VodGetPlaylistsResult_descriptor;
    }

    @java.lang.Override
    public com.byteplus.service.vod.model.business.VodGetPlaylistsResult getDefaultInstanceForType() {
      return com.byteplus.service.vod.model.business.VodGetPlaylistsResult.getDefaultInstance();
    }

    @java.lang.Override
    public com.byteplus.service.vod.model.business.VodGetPlaylistsResult build() {
      com.byteplus.service.vod.model.business.VodGetPlaylistsResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.byteplus.service.vod.model.business.VodGetPlaylistsResult buildPartial() {
      com.byteplus.service.vod.model.business.VodGetPlaylistsResult result = new com.byteplus.service.vod.model.business.VodGetPlaylistsResult(this);
      int from_bitField0_ = bitField0_;
      if (playlistsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          playlists_ = java.util.Collections.unmodifiableList(playlists_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.playlists_ = playlists_;
      } else {
        result.playlists_ = playlistsBuilder_.build();
      }
      if (invalidPlaylistsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          invalidPlaylists_ = java.util.Collections.unmodifiableList(invalidPlaylists_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.invalidPlaylists_ = invalidPlaylists_;
      } else {
        result.invalidPlaylists_ = invalidPlaylistsBuilder_.build();
      }
      result.total_ = total_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.byteplus.service.vod.model.business.VodGetPlaylistsResult) {
        return mergeFrom((com.byteplus.service.vod.model.business.VodGetPlaylistsResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.byteplus.service.vod.model.business.VodGetPlaylistsResult other) {
      if (other == com.byteplus.service.vod.model.business.VodGetPlaylistsResult.getDefaultInstance()) return this;
      if (playlistsBuilder_ == null) {
        if (!other.playlists_.isEmpty()) {
          if (playlists_.isEmpty()) {
            playlists_ = other.playlists_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePlaylistsIsMutable();
            playlists_.addAll(other.playlists_);
          }
          onChanged();
        }
      } else {
        if (!other.playlists_.isEmpty()) {
          if (playlistsBuilder_.isEmpty()) {
            playlistsBuilder_.dispose();
            playlistsBuilder_ = null;
            playlists_ = other.playlists_;
            bitField0_ = (bitField0_ & ~0x00000001);
            playlistsBuilder_ =
                    com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                            getPlaylistsFieldBuilder() : null;
          } else {
            playlistsBuilder_.addAllMessages(other.playlists_);
          }
        }
      }
      if (invalidPlaylistsBuilder_ == null) {
        if (!other.invalidPlaylists_.isEmpty()) {
          if (invalidPlaylists_.isEmpty()) {
            invalidPlaylists_ = other.invalidPlaylists_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureInvalidPlaylistsIsMutable();
            invalidPlaylists_.addAll(other.invalidPlaylists_);
          }
          onChanged();
        }
      } else {
        if (!other.invalidPlaylists_.isEmpty()) {
          if (invalidPlaylistsBuilder_.isEmpty()) {
            invalidPlaylistsBuilder_.dispose();
            invalidPlaylistsBuilder_ = null;
            invalidPlaylists_ = other.invalidPlaylists_;
            bitField0_ = (bitField0_ & ~0x00000002);
            invalidPlaylistsBuilder_ =
                    com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                            getInvalidPlaylistsFieldBuilder() : null;
          } else {
            invalidPlaylistsBuilder_.addAllMessages(other.invalidPlaylists_);
          }
        }
      }
      if (other.getTotal() != 0) {
        setTotal(other.getTotal());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      com.byteplus.service.vod.model.business.VodGetPlaylistsResult parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.byteplus.service.vod.model.business.VodGetPlaylistsResult) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.byteplus.service.vod.model.business.VodPlaylistInfo> playlists_ =
            java.util.Collections.emptyList();
    private void ensurePlaylistsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        playlists_ = new java.util.ArrayList<com.byteplus.service.vod.model.business.VodPlaylistInfo>(playlists_);
        bitField0_ |= 0x00000001;
      }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            com.byteplus.service.vod.model.business.VodPlaylistInfo, com.byteplus.service.vod.model.business.VodPlaylistInfo.Builder, com.byteplus.service.vod.model.business.VodPlaylistInfoOrBuilder> playlistsBuilder_;

    /**
     * <code>repeated .Byteplus.Vod.Models.Business.VodPlaylistInfo Playlists = 1;</code>
     */
    public java.util.List<com.byteplus.service.vod.model.business.VodPlaylistInfo> getPlaylistsList() {
      if (playlistsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(playlists_);
      } else {
        return playlistsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Byteplus.Vod.Models.Business.VodPlaylistInfo Playlists = 1;</code>
     */
    public int getPlaylistsCount() {
      if (playlistsBuilder_ == null) {
        return playlists_.size();
      } else {
        return playlistsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Byteplus.Vod.Models.Business.VodPlaylistInfo Playlists = 1;</code>
     */
    public com.byteplus.service.vod.model.business.VodPlaylistInfo getPlaylists(int index) {
      if (playlistsBuilder_ == null) {
        return playlists_.get(index);
      } else {
        return playlistsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Byteplus.Vod.Models.Business.VodPlaylistInfo Playlists = 1;</code>
     */
    public Builder setPlaylists(
            int index, com.byteplus.service.vod.model.business.VodPlaylistInfo value) {
      if (playlistsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlaylistsIsMutable();
        playlists_.set(index, value);
        onChanged();
      } else {
        playlistsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Byteplus.Vod.Models.Business.VodPlaylistInfo Playlists = 1;</code>
     */
    public Builder setPlaylists(
            int index, com.byteplus.service.vod.model.business.VodPlaylistInfo.Builder builderForValue) {
      if (playlistsBuilder_ == null) {
        ensurePlaylistsIsMutable();
        playlists_.set(index, builderForValue.build());
        onChanged();
      } else {
        playlistsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Byteplus.Vod.Models.Business.VodPlaylistInfo Playlists = 1;</code>
     */
    public Builder addPlaylists(com.byteplus.service.vod.model.business.VodPlaylistInfo value) {
      if (playlistsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlaylistsIsMutable();
        playlists_.add(value);
        onChanged();
      } else {
        playlistsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Byteplus.Vod.Models.Business.VodPlaylistInfo Playlists = 1;</code>
     */
    public Builder addPlaylists(
            int index, com.byteplus.service.vod.model.business.VodPlaylistInfo value) {
      if (playlistsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePlaylistsIsMutable();
        playlists_.add(index, value);
        onChanged();
      } else {
        playlistsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Byteplus.Vod.Models.Business.VodPlaylistInfo Playlists = 1;</code>
     */
    public Builder addPlaylists(
            com.byteplus.service.vod.model.business.VodPlaylistInfo.Builder builderForValue) {
      if (playlistsBuilder_ == null) {
        ensurePlaylistsIsMutable();
        playlists_.add(builderForValue.build());
        onChanged();
      } else {
        playlistsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Byteplus.Vod.Models.Business.VodPlaylistInfo Playlists = 1;</code>
     */
    public Builder addPlaylists(
            int index, com.byteplus.service.vod.model.business.VodPlaylistInfo.Builder builderForValue) {
      if (playlistsBuilder_ == null) {
        ensurePlaylistsIsMutable();
        playlists_.add(index, builderForValue.build());
        onChanged();
      } else {
        playlistsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Byteplus.Vod.Models.Business.VodPlaylistInfo Playlists = 1;</code>
     */
    public Builder addAllPlaylists(
            java.lang.Iterable<? extends com.byteplus.service.vod.model.business.VodPlaylistInfo> values) {
      if (playlistsBuilder_ == null) {
        ensurePlaylistsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
                values, playlists_);
        onChanged();
      } else {
        playlistsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Byteplus.Vod.Models.Business.VodPlaylistInfo Playlists = 1;</code>
     */
    public Builder clearPlaylists() {
      if (playlistsBuilder_ == null) {
        playlists_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        playlistsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Byteplus.Vod.Models.Business.VodPlaylistInfo Playlists = 1;</code>
     */
    public Builder removePlaylists(int index) {
      if (playlistsBuilder_ == null) {
        ensurePlaylistsIsMutable();
        playlists_.remove(index);
        onChanged();
      } else {
        playlistsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Byteplus.Vod.Models.Business.VodPlaylistInfo Playlists = 1;</code>
     */
    public com.byteplus.service.vod.model.business.VodPlaylistInfo.Builder getPlaylistsBuilder(
            int index) {
      return getPlaylistsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Byteplus.Vod.Models.Business.VodPlaylistInfo Playlists = 1;</code>
     */
    public com.byteplus.service.vod.model.business.VodPlaylistInfoOrBuilder getPlaylistsOrBuilder(
            int index) {
      if (playlistsBuilder_ == null) {
        return playlists_.get(index);  } else {
        return playlistsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Byteplus.Vod.Models.Business.VodPlaylistInfo Playlists = 1;</code>
     */
    public java.util.List<? extends com.byteplus.service.vod.model.business.VodPlaylistInfoOrBuilder>
    getPlaylistsOrBuilderList() {
      if (playlistsBuilder_ != null) {
        return playlistsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(playlists_);
      }
    }
    /**
     * <code>repeated .Byteplus.Vod.Models.Business.VodPlaylistInfo Playlists = 1;</code>
     */
    public com.byteplus.service.vod.model.business.VodPlaylistInfo.Builder addPlaylistsBuilder() {
      return getPlaylistsFieldBuilder().addBuilder(
              com.byteplus.service.vod.model.business.VodPlaylistInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .Byteplus.Vod.Models.Business.VodPlaylistInfo Playlists = 1;</code>
     */
    public com.byteplus.service.vod.model.business.VodPlaylistInfo.Builder addPlaylistsBuilder(
            int index) {
      return getPlaylistsFieldBuilder().addBuilder(
              index, com.byteplus.service.vod.model.business.VodPlaylistInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .Byteplus.Vod.Models.Business.VodPlaylistInfo Playlists = 1;</code>
     */
    public java.util.List<com.byteplus.service.vod.model.business.VodPlaylistInfo.Builder>
    getPlaylistsBuilderList() {
      return getPlaylistsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
            com.byteplus.service.vod.model.business.VodPlaylistInfo, com.byteplus.service.vod.model.business.VodPlaylistInfo.Builder, com.byteplus.service.vod.model.business.VodPlaylistInfoOrBuilder>
    getPlaylistsFieldBuilder() {
      if (playlistsBuilder_ == null) {
        playlistsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                com.byteplus.service.vod.model.business.VodPlaylistInfo, com.byteplus.service.vod.model.business.VodPlaylistInfo.Builder, com.byteplus.service.vod.model.business.VodPlaylistInfoOrBuilder>(
                playlists_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        playlists_ = null;
      }
      return playlistsBuilder_;
    }

    private java.util.List<com.byteplus.service.vod.model.business.InvalidPlaylist> invalidPlaylists_ =
            java.util.Collections.emptyList();
    private void ensureInvalidPlaylistsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        invalidPlaylists_ = new java.util.ArrayList<com.byteplus.service.vod.model.business.InvalidPlaylist>(invalidPlaylists_);
        bitField0_ |= 0x00000002;
      }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            com.byteplus.service.vod.model.business.InvalidPlaylist, com.byteplus.service.vod.model.business.InvalidPlaylist.Builder, com.byteplus.service.vod.model.business.InvalidPlaylistOrBuilder> invalidPlaylistsBuilder_;

    /**
     * <code>repeated .Byteplus.Vod.Models.Business.InvalidPlaylist InvalidPlaylists = 2;</code>
     */
    public java.util.List<com.byteplus.service.vod.model.business.InvalidPlaylist> getInvalidPlaylistsList() {
      if (invalidPlaylistsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(invalidPlaylists_);
      } else {
        return invalidPlaylistsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Byteplus.Vod.Models.Business.InvalidPlaylist InvalidPlaylists = 2;</code>
     */
    public int getInvalidPlaylistsCount() {
      if (invalidPlaylistsBuilder_ == null) {
        return invalidPlaylists_.size();
      } else {
        return invalidPlaylistsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Byteplus.Vod.Models.Business.InvalidPlaylist InvalidPlaylists = 2;</code>
     */
    public com.byteplus.service.vod.model.business.InvalidPlaylist getInvalidPlaylists(int index) {
      if (invalidPlaylistsBuilder_ == null) {
        return invalidPlaylists_.get(index);
      } else {
        return invalidPlaylistsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Byteplus.Vod.Models.Business.InvalidPlaylist InvalidPlaylists = 2;</code>
     */
    public Builder setInvalidPlaylists(
            int index, com.byteplus.service.vod.model.business.InvalidPlaylist value) {
      if (invalidPlaylistsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInvalidPlaylistsIsMutable();
        invalidPlaylists_.set(index, value);
        onChanged();
      } else {
        invalidPlaylistsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Byteplus.Vod.Models.Business.InvalidPlaylist InvalidPlaylists = 2;</code>
     */
    public Builder setInvalidPlaylists(
            int index, com.byteplus.service.vod.model.business.InvalidPlaylist.Builder builderForValue) {
      if (invalidPlaylistsBuilder_ == null) {
        ensureInvalidPlaylistsIsMutable();
        invalidPlaylists_.set(index, builderForValue.build());
        onChanged();
      } else {
        invalidPlaylistsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Byteplus.Vod.Models.Business.InvalidPlaylist InvalidPlaylists = 2;</code>
     */
    public Builder addInvalidPlaylists(com.byteplus.service.vod.model.business.InvalidPlaylist value) {
      if (invalidPlaylistsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInvalidPlaylistsIsMutable();
        invalidPlaylists_.add(value);
        onChanged();
      } else {
        invalidPlaylistsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Byteplus.Vod.Models.Business.InvalidPlaylist InvalidPlaylists = 2;</code>
     */
    public Builder addInvalidPlaylists(
            int index, com.byteplus.service.vod.model.business.InvalidPlaylist value) {
      if (invalidPlaylistsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInvalidPlaylistsIsMutable();
        invalidPlaylists_.add(index, value);
        onChanged();
      } else {
        invalidPlaylistsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Byteplus.Vod.Models.Business.InvalidPlaylist InvalidPlaylists = 2;</code>
     */
    public Builder addInvalidPlaylists(
            com.byteplus.service.vod.model.business.InvalidPlaylist.Builder builderForValue) {
      if (invalidPlaylistsBuilder_ == null) {
        ensureInvalidPlaylistsIsMutable();
        invalidPlaylists_.add(builderForValue.build());
        onChanged();
      } else {
        invalidPlaylistsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Byteplus.Vod.Models.Business.InvalidPlaylist InvalidPlaylists = 2;</code>
     */
    public Builder addInvalidPlaylists(
            int index, com.byteplus.service.vod.model.business.InvalidPlaylist.Builder builderForValue) {
      if (invalidPlaylistsBuilder_ == null) {
        ensureInvalidPlaylistsIsMutable();
        invalidPlaylists_.add(index, builderForValue.build());
        onChanged();
      } else {
        invalidPlaylistsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Byteplus.Vod.Models.Business.InvalidPlaylist InvalidPlaylists = 2;</code>
     */
    public Builder addAllInvalidPlaylists(
            java.lang.Iterable<? extends com.byteplus.service.vod.model.business.InvalidPlaylist> values) {
      if (invalidPlaylistsBuilder_ == null) {
        ensureInvalidPlaylistsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
                values, invalidPlaylists_);
        onChanged();
      } else {
        invalidPlaylistsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Byteplus.Vod.Models.Business.InvalidPlaylist InvalidPlaylists = 2;</code>
     */
    public Builder clearInvalidPlaylists() {
      if (invalidPlaylistsBuilder_ == null) {
        invalidPlaylists_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        invalidPlaylistsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Byteplus.Vod.Models.Business.InvalidPlaylist InvalidPlaylists = 2;</code>
     */
    public Builder removeInvalidPlaylists(int index) {
      if (invalidPlaylistsBuilder_ == null) {
        ensureInvalidPlaylistsIsMutable();
        invalidPlaylists_.remove(index);
        onChanged();
      } else {
        invalidPlaylistsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Byteplus.Vod.Models.Business.InvalidPlaylist InvalidPlaylists = 2;</code>
     */
    public com.byteplus.service.vod.model.business.InvalidPlaylist.Builder getInvalidPlaylistsBuilder(
            int index) {
      return getInvalidPlaylistsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Byteplus.Vod.Models.Business.InvalidPlaylist InvalidPlaylists = 2;</code>
     */
    public com.byteplus.service.vod.model.business.InvalidPlaylistOrBuilder getInvalidPlaylistsOrBuilder(
            int index) {
      if (invalidPlaylistsBuilder_ == null) {
        return invalidPlaylists_.get(index);  } else {
        return invalidPlaylistsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Byteplus.Vod.Models.Business.InvalidPlaylist InvalidPlaylists = 2;</code>
     */
    public java.util.List<? extends com.byteplus.service.vod.model.business.InvalidPlaylistOrBuilder>
    getInvalidPlaylistsOrBuilderList() {
      if (invalidPlaylistsBuilder_ != null) {
        return invalidPlaylistsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(invalidPlaylists_);
      }
    }
    /**
     * <code>repeated .Byteplus.Vod.Models.Business.InvalidPlaylist InvalidPlaylists = 2;</code>
     */
    public com.byteplus.service.vod.model.business.InvalidPlaylist.Builder addInvalidPlaylistsBuilder() {
      return getInvalidPlaylistsFieldBuilder().addBuilder(
              com.byteplus.service.vod.model.business.InvalidPlaylist.getDefaultInstance());
    }
    /**
     * <code>repeated .Byteplus.Vod.Models.Business.InvalidPlaylist InvalidPlaylists = 2;</code>
     */
    public com.byteplus.service.vod.model.business.InvalidPlaylist.Builder addInvalidPlaylistsBuilder(
            int index) {
      return getInvalidPlaylistsFieldBuilder().addBuilder(
              index, com.byteplus.service.vod.model.business.InvalidPlaylist.getDefaultInstance());
    }
    /**
     * <code>repeated .Byteplus.Vod.Models.Business.InvalidPlaylist InvalidPlaylists = 2;</code>
     */
    public java.util.List<com.byteplus.service.vod.model.business.InvalidPlaylist.Builder>
    getInvalidPlaylistsBuilderList() {
      return getInvalidPlaylistsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
            com.byteplus.service.vod.model.business.InvalidPlaylist, com.byteplus.service.vod.model.business.InvalidPlaylist.Builder, com.byteplus.service.vod.model.business.InvalidPlaylistOrBuilder>
    getInvalidPlaylistsFieldBuilder() {
      if (invalidPlaylistsBuilder_ == null) {
        invalidPlaylistsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                com.byteplus.service.vod.model.business.InvalidPlaylist, com.byteplus.service.vod.model.business.InvalidPlaylist.Builder, com.byteplus.service.vod.model.business.InvalidPlaylistOrBuilder>(
                invalidPlaylists_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        invalidPlaylists_ = null;
      }
      return invalidPlaylistsBuilder_;
    }

    private int total_ ;
    /**
     * <code>int32 Total = 3;</code>
     * @return The total.
     */
    @java.lang.Override
    public int getTotal() {
      return total_;
    }
    /**
     * <code>int32 Total = 3;</code>
     * @param value The total to set.
     * @return This builder for chaining.
     */
    public Builder setTotal(int value) {

      total_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 Total = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotal() {

      total_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Byteplus.Vod.Models.Business.VodGetPlaylistsResult)
  }

  // @@protoc_insertion_point(class_scope:Byteplus.Vod.Models.Business.VodGetPlaylistsResult)
  private static final com.byteplus.service.vod.model.business.VodGetPlaylistsResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.byteplus.service.vod.model.business.VodGetPlaylistsResult();
  }

  public static com.byteplus.service.vod.model.business.VodGetPlaylistsResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VodGetPlaylistsResult>
          PARSER = new com.google.protobuf.AbstractParser<VodGetPlaylistsResult>() {
    @java.lang.Override
    public VodGetPlaylistsResult parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return new VodGetPlaylistsResult(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<VodGetPlaylistsResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<VodGetPlaylistsResult> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.byteplus.service.vod.model.business.VodGetPlaylistsResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

