// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: byteplus/vod/business/vod_media.proto

package com.byteplus.service.vod.model.business;

public interface VodGetFramesForAuditResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Byteplus.Vod.Models.Business.VodGetFramesForAuditResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 帧列表
   * </pre>
   *
   * <code>repeated .Byteplus.Vod.Models.Business.VodFrameDataForAudit Frames = 1;</code>
   */
  java.util.List<com.byteplus.service.vod.model.business.VodFrameDataForAudit> 
      getFramesList();
  /**
   * <pre>
   * 帧列表
   * </pre>
   *
   * <code>repeated .Byteplus.Vod.Models.Business.VodFrameDataForAudit Frames = 1;</code>
   */
  com.byteplus.service.vod.model.business.VodFrameDataForAudit getFrames(int index);
  /**
   * <pre>
   * 帧列表
   * </pre>
   *
   * <code>repeated .Byteplus.Vod.Models.Business.VodFrameDataForAudit Frames = 1;</code>
   */
  int getFramesCount();
  /**
   * <pre>
   * 帧列表
   * </pre>
   *
   * <code>repeated .Byteplus.Vod.Models.Business.VodFrameDataForAudit Frames = 1;</code>
   */
  java.util.List<? extends com.byteplus.service.vod.model.business.VodFrameDataForAuditOrBuilder> 
      getFramesOrBuilderList();
  /**
   * <pre>
   * 帧列表
   * </pre>
   *
   * <code>repeated .Byteplus.Vod.Models.Business.VodFrameDataForAudit Frames = 1;</code>
   */
  com.byteplus.service.vod.model.business.VodFrameDataForAuditOrBuilder getFramesOrBuilder(
      int index);
}
