// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: byteplus/vod/business/vod_media.proto

package com.byteplus.service.vod.model.business;

public interface VodGetAutomaticSpeechRecognitionForAuditResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Byteplus.Vod.Models.Business.VodGetAutomaticSpeechRecognitionForAuditResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Byteplus.Vod.Models.Business.VodASRInfoForAudit Info = 1;</code>
   * @return Whether the info field is set.
   */
  boolean hasInfo();
  /**
   * <code>.Byteplus.Vod.Models.Business.VodASRInfoForAudit Info = 1;</code>
   * @return The info.
   */
  com.byteplus.service.vod.model.business.VodASRInfoForAudit getInfo();
  /**
   * <code>.Byteplus.Vod.Models.Business.VodASRInfoForAudit Info = 1;</code>
   */
  com.byteplus.service.vod.model.business.VodASRInfoForAuditOrBuilder getInfoOrBuilder();
}
