// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: byteplus/vod/business/vod_common.proto

package com.byteplus.service.vod.model.business;

public interface VodGetFairPlayCertInfoResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Byteplus.Vod.Models.Business.VodGetFairPlayCertInfoResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string CertId = 1;</code>
   * @return The certId.
   */
  java.lang.String getCertId();
  /**
   * <code>string CertId = 1;</code>
   * @return The bytes for certId.
   */
  com.google.protobuf.ByteString
      getCertIdBytes();

  /**
   * <code>string CertName = 2;</code>
   * @return The certName.
   */
  java.lang.String getCertName();
  /**
   * <code>string CertName = 2;</code>
   * @return The bytes for certName.
   */
  com.google.protobuf.ByteString
      getCertNameBytes();

  /**
   * <code>string CertFileName = 3;</code>
   * @return The certFileName.
   */
  java.lang.String getCertFileName();
  /**
   * <code>string CertFileName = 3;</code>
   * @return The bytes for certFileName.
   */
  com.google.protobuf.ByteString
      getCertFileNameBytes();

  /**
   * <code>string PkFileName = 4;</code>
   * @return The pkFileName.
   */
  java.lang.String getPkFileName();
  /**
   * <code>string PkFileName = 4;</code>
   * @return The bytes for pkFileName.
   */
  com.google.protobuf.ByteString
      getPkFileNameBytes();

  /**
   * <code>string PkPassword = 5;</code>
   * @return The pkPassword.
   */
  java.lang.String getPkPassword();
  /**
   * <code>string PkPassword = 5;</code>
   * @return The bytes for pkPassword.
   */
  com.google.protobuf.ByteString
      getPkPasswordBytes();

  /**
   * <code>string Ask = 6;</code>
   * @return The ask.
   */
  java.lang.String getAsk();
  /**
   * <code>string Ask = 6;</code>
   * @return The bytes for ask.
   */
  com.google.protobuf.ByteString
      getAskBytes();
}
