// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: byteplus/vod/business/vod_workflow.proto

package com.byteplus.service.vod.model.business;

public interface VodListWorkflowExecutionResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Byteplus.Vod.Models.Business.VodListWorkflowExecutionResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 工作流记录
   * </pre>
   *
   * <code>repeated .Byteplus.Vod.Models.Business.WorkflowExecution Data = 1;</code>
   */
  java.util.List<com.byteplus.service.vod.model.business.WorkflowExecution> 
      getDataList();
  /**
   * <pre>
   * 工作流记录
   * </pre>
   *
   * <code>repeated .Byteplus.Vod.Models.Business.WorkflowExecution Data = 1;</code>
   */
  com.byteplus.service.vod.model.business.WorkflowExecution getData(int index);
  /**
   * <pre>
   * 工作流记录
   * </pre>
   *
   * <code>repeated .Byteplus.Vod.Models.Business.WorkflowExecution Data = 1;</code>
   */
  int getDataCount();
  /**
   * <pre>
   * 工作流记录
   * </pre>
   *
   * <code>repeated .Byteplus.Vod.Models.Business.WorkflowExecution Data = 1;</code>
   */
  java.util.List<? extends com.byteplus.service.vod.model.business.WorkflowExecutionOrBuilder> 
      getDataOrBuilderList();
  /**
   * <pre>
   * 工作流记录
   * </pre>
   *
   * <code>repeated .Byteplus.Vod.Models.Business.WorkflowExecution Data = 1;</code>
   */
  com.byteplus.service.vod.model.business.WorkflowExecutionOrBuilder getDataOrBuilder(
      int index);

  /**
   * <pre>
   * 符合条件的结果总数
   * </pre>
   *
   * <code>int32 TotalCount = 2;</code>
   * @return The totalCount.
   */
  int getTotalCount();

  /**
   * <pre>
   * 分页大小
   * </pre>
   *
   * <code>int32 PageSize = 3;</code>
   * @return The pageSize.
   */
  int getPageSize();

  /**
   * <pre>
   * 数据偏移量
   * </pre>
   *
   * <code>int32 Offset = 4;</code>
   * @return The offset.
   */
  int getOffset();
}
