// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: byteplus/vod/business/vod_media.proto

package com.byteplus.service.vod.model.business;

public interface VodMediaSmartInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Byteplus.Vod.Models.Business.VodMediaSmartInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *空间名
   * </pre>
   *
   * <code>string SpaceName = 1;</code>
   * @return The spaceName.
   */
  java.lang.String getSpaceName();
  /**
   * <pre>
   *空间名
   * </pre>
   *
   * <code>string SpaceName = 1;</code>
   * @return The bytes for spaceName.
   */
  com.google.protobuf.ByteString
      getSpaceNameBytes();

  /**
   * <code>string Vid = 2;</code>
   * @return The vid.
   */
  java.lang.String getVid();
  /**
   * <code>string Vid = 2;</code>
   * @return The bytes for vid.
   */
  com.google.protobuf.ByteString
      getVidBytes();

  /**
   * <pre>
   *智能标签列表
   * </pre>
   *
   * <code>repeated string SmartTags = 3;</code>
   * @return A list containing the smartTags.
   */
  java.util.List<java.lang.String>
      getSmartTagsList();
  /**
   * <pre>
   *智能标签列表
   * </pre>
   *
   * <code>repeated string SmartTags = 3;</code>
   * @return The count of smartTags.
   */
  int getSmartTagsCount();
  /**
   * <pre>
   *智能标签列表
   * </pre>
   *
   * <code>repeated string SmartTags = 3;</code>
   * @param index The index of the element to return.
   * @return The smartTags at the given index.
   */
  java.lang.String getSmartTags(int index);
  /**
   * <pre>
   *智能标签列表
   * </pre>
   *
   * <code>repeated string SmartTags = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the smartTags at the given index.
   */
  com.google.protobuf.ByteString
      getSmartTagsBytes(int index);
}
