// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: byteplus/vod/business/vod_media.proto

package com.byteplus.service.vod.model.business;

public interface VodVideoClassificationsDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Byteplus.Vod.Models.Business.VodVideoClassificationsData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Byteplus.Vod.Models.Business.VodClassification ClassificationTrees = 1;</code>
   */
  java.util.List<com.byteplus.service.vod.model.business.VodClassification> 
      getClassificationTreesList();
  /**
   * <code>repeated .Byteplus.Vod.Models.Business.VodClassification ClassificationTrees = 1;</code>
   */
  com.byteplus.service.vod.model.business.VodClassification getClassificationTrees(int index);
  /**
   * <code>repeated .Byteplus.Vod.Models.Business.VodClassification ClassificationTrees = 1;</code>
   */
  int getClassificationTreesCount();
  /**
   * <code>repeated .Byteplus.Vod.Models.Business.VodClassification ClassificationTrees = 1;</code>
   */
  java.util.List<? extends com.byteplus.service.vod.model.business.VodClassificationOrBuilder> 
      getClassificationTreesOrBuilderList();
  /**
   * <code>repeated .Byteplus.Vod.Models.Business.VodClassification ClassificationTrees = 1;</code>
   */
  com.byteplus.service.vod.model.business.VodClassificationOrBuilder getClassificationTreesOrBuilder(
      int index);
}
