// Code generated by protoc-gen-byteplus-sdk
// source: createCdnPreloadTask
// DO NOT EDIT!

package com.byteplus.example.vod.cdn;

import com.byteplus.service.vod.IVodService;
import com.byteplus.service.vod.impl.VodServiceImpl;
public class VodCreateCdnPreloadTaskDemo {

    public static void main(String[] args) throws Exception {
        IVodService vodService = VodServiceImpl.getInstance();
        vodService.setAccessKey("your ak");
        vodService.setSecretKey("your sk");

        try {
            com.byteplus.service.vod.model.request.VodCreateCdnPreloadTaskRequest.Builder reqBuilder = com.byteplus.service.vod.model.request.VodCreateCdnPreloadTaskRequest.newBuilder();
			reqBuilder.setSpaceName("your SpaceName");
			reqBuilder.setUrls("your Urls");
			
            com.byteplus.service.vod.model.response.VodCreateCdnPreloadTaskResponse resp = vodService.createCdnPreloadTask(reqBuilder.build());
            if (resp.getResponseMetadata().hasError()) {
                System.out.println(resp.getResponseMetadata().getError());
                System.exit(-1);
            }
            System.out.println(resp);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}