// Code generated by protoc-gen-byteplus-sdk
// source: describeIpInfo
// DO NOT EDIT!

package com.byteplus.example.vod.cdn;

import com.byteplus.service.vod.IVodService;
import com.byteplus.service.vod.impl.VodServiceImpl;
public class VodDescribeIpInfoDemo {

    public static void main(String[] args) throws Exception {
        IVodService vodService = VodServiceImpl.getInstance();
        vodService.setAccessKey("your ak");
        vodService.setSecretKey("your sk");

        try {
            com.byteplus.service.vod.model.request.VodDescribeIPInfoRequest.Builder reqBuilder = com.byteplus.service.vod.model.request.VodDescribeIPInfoRequest.newBuilder();
			reqBuilder.setIps("your Ips");
			
            com.byteplus.service.vod.model.response.VodDescribeIPInfoResponse resp = vodService.describeIpInfo(reqBuilder.build());
            if (resp.getResponseMetadata().hasError()) {
                System.out.println(resp.getResponseMetadata().getError());
                System.exit(-1);
            }
            System.out.println(resp);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}