// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: byteplus/vod/response/response_vod.proto

package com.byteplus.service.vod.model.response;

public interface VodApplyUploadInfoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Byteplus.Vod.Models.Response.VodApplyUploadInfoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 通用返回结构 
   * </pre>
   *
   * <code>.Byteplus.Base.Models.Base.ResponseMetadata ResponseMetadata = 1;</code>
   * @return Whether the responseMetadata field is set.
   */
  boolean hasResponseMetadata();
  /**
   * <pre>
   * 通用返回结构 
   * </pre>
   *
   * <code>.Byteplus.Base.Models.Base.ResponseMetadata ResponseMetadata = 1;</code>
   * @return The responseMetadata.
   */
  com.byteplus.service.base.model.base.ResponseMetadata getResponseMetadata();
  /**
   * <pre>
   * 通用返回结构 
   * </pre>
   *
   * <code>.Byteplus.Base.Models.Base.ResponseMetadata ResponseMetadata = 1;</code>
   */
  com.byteplus.service.base.model.base.ResponseMetadataOrBuilder getResponseMetadataOrBuilder();

  /**
   * <pre>
   * 视频上传 1001 阶段返回结果 
   * </pre>
   *
   * <code>.Byteplus.Vod.Models.Business.VodApplyUploadInfoResult Result = 2;</code>
   * @return Whether the result field is set.
   */
  boolean hasResult();
  /**
   * <pre>
   * 视频上传 1001 阶段返回结果 
   * </pre>
   *
   * <code>.Byteplus.Vod.Models.Business.VodApplyUploadInfoResult Result = 2;</code>
   * @return The result.
   */
  com.byteplus.service.vod.model.business.VodApplyUploadInfoResult getResult();
  /**
   * <pre>
   * 视频上传 1001 阶段返回结果 
   * </pre>
   *
   * <code>.Byteplus.Vod.Models.Business.VodApplyUploadInfoResult Result = 2;</code>
   */
  com.byteplus.service.vod.model.business.VodApplyUploadInfoResultOrBuilder getResultOrBuilder();
}
