// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: byteplus/vod/response/response_vod.proto

package com.byteplus.service.vod.model.response;

public final class VodResponse {
  private VodResponse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodGetAllPlayInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodGetAllPlayInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodGetPlayInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodGetPlayInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodGetOriginalPlayInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodGetOriginalPlayInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodGetPrivateDrmPlayAuthResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodGetPrivateDrmPlayAuthResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodGetHlsDecryptionKeyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodGetHlsDecryptionKeyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodGetPlayInfoWithLiveTimeShiftSceneResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodGetPlayInfoWithLiveTimeShiftSceneResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodUploadMediaResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodUploadMediaResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodQueryUploadTaskInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodQueryUploadTaskInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodUrlUploadResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodUrlUploadResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodApplyUploadInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodApplyUploadInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodCommitUploadInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodCommitUploadInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodGetMediaInfosResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodGetMediaInfosResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodUpdateMediaInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodUpdateMediaInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodGetRecommendedPosterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodGetRecommendedPosterResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodUpdateMediaPublishStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodUpdateMediaPublishStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodUpdateMediaStorageClassResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodUpdateMediaStorageClassResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodDeleteMediaResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodDeleteMediaResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodDeleteTranscodesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodDeleteTranscodesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodGetMediaListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodGetMediaListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodGetSubtitleInfoListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodGetSubtitleInfoListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodUpdateSubtitleStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodUpdateSubtitleStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodUpdateSubtitleInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodUpdateSubtitleInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodGetAuditFramesForAuditResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodGetAuditFramesForAuditResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodGetMLFramesForAuditResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodGetMLFramesForAuditResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodGetBetterFramesForAuditResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodGetBetterFramesForAuditResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodGetAudioInfoForAuditResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodGetAudioInfoForAuditResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodGetAutomaticSpeechRecognitionForAuditResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodGetAutomaticSpeechRecognitionForAuditResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodGetAudioEventDetectionForAuditResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodGetAudioEventDetectionForAuditResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodCreateVideoClassificationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodCreateVideoClassificationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodUpdateVideoClassificationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodUpdateVideoClassificationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodDeleteVideoClassificationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodDeleteVideoClassificationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodListVideoClassificationsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodListVideoClassificationsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodListSnapshotsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodListSnapshotsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodGetFileListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodGetFileListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodExtractMediaMetaTaskResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodExtractMediaMetaTaskResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodStartWorkflowResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodStartWorkflowResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodRetrieveTranscodeResultResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodRetrieveTranscodeResultResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodListWorkflowExecutionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodListWorkflowExecutionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodGetWorkflowExecutionDetailResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodGetWorkflowExecutionDetailResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodGetWorkflowExecutionStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodGetWorkflowExecutionStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodGetWorkflowResultResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodGetWorkflowResultResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodSubmitDirectEditTaskAsyncResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodSubmitDirectEditTaskAsyncResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodGetDirectEditProgressResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodGetDirectEditProgressResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodGetDirectEditResultResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodGetDirectEditResultResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodCreateSpaceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodCreateSpaceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodListSpaceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodListSpaceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodGetSpaceDetailResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodGetSpaceDetailResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodUpdateSpaceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodUpdateSpaceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodUpdateSpaceUploadConfigResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodUpdateSpaceUploadConfigResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodDescribeVodSpaceStorageDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodDescribeVodSpaceStorageDataResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodListDomainResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodListDomainResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodCreateCdnRefreshTaskResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodCreateCdnRefreshTaskResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodCreateCdnPreloadTaskResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodCreateCdnPreloadTaskResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodListCdnTasksResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodListCdnTasksResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodListCdnAccessLogResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodListCdnAccessLogResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodListCdnTopAccessUrlResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodListCdnTopAccessUrlResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodDescribeVodDomainBandwidthDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodDescribeVodDomainBandwidthDataResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodCdnStatisticsCommonResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodCdnStatisticsCommonResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodDescribeIPInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodDescribeIPInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodDescribeVodDomainTrafficDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodDescribeVodDomainTrafficDataResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodSubmitBlockTasksResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodSubmitBlockTasksResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodGetContentBlockTasksResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodGetContentBlockTasksResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodCreateDomainV2Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodCreateDomainV2Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodUpdateDomainExpireV2Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodUpdateDomainExpireV2Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodUpdateDomainAuthConfigV2Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodUpdateDomainAuthConfigV2Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodAddCallbackSubscriptionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodAddCallbackSubscriptionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodSetCallbackEventResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodSetCallbackEventResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodGetSmartStrategyLitePlayInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodGetSmartStrategyLitePlayInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodGetAppInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodGetAppInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_DescribeVodSpaceTranscodeDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_DescribeVodSpaceTranscodeDataResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_DescribeVodSpaceAIStatisDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_DescribeVodSpaceAIStatisDataResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_DescribeVodSpaceSubtitleStatisDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_DescribeVodSpaceSubtitleStatisDataResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_DescribeVodSpaceDetectStatisDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_DescribeVodSpaceDetectStatisDataResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_DescribeVodSnapshotDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_DescribeVodSnapshotDataResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_DescribeVodSpaceWorkflowDetailDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_DescribeVodSpaceWorkflowDetailDataResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_DescribeVodSpaceEditDetailDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_DescribeVodSpaceEditDetailDataResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_DescribeVodPlayFileLogByDomainResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_DescribeVodPlayFileLogByDomainResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodSubmitBlockMediaTaskResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodSubmitBlockMediaTaskResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodSubmitUnblockMediaTaskResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodSubmitUnblockMediaTaskResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodQueryMediaBlockStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodQueryMediaBlockStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodCreatePlaylistResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodCreatePlaylistResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodGetPlaylistsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodGetPlaylistsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodUpdatePlaylistResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodUpdatePlaylistResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Vod_Models_Response_VodDeletePlaylistResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Vod_Models_Response_VodDeletePlaylistResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(byteplus/vod/response/response_vod.pro" +
      "to\022\034Byteplus.Vod.Models.Response\032\030bytepl" +
      "us/base/base.proto\032$byteplus/vod/busines" +
      "s/vod_play.proto\032%byteplus/vod/business/" +
      "vod_media.proto\032&byteplus/vod/business/v" +
      "od_upload.proto\032(byteplus/vod/business/v" +
      "od_workflow.proto\032$byteplus/vod/business" +
      "/vod_edit.proto\032%byteplus/vod/business/v" +
      "od_space.proto\032#byteplus/vod/business/vo" +
      "d_cdn.proto\032&byteplus/vod/business/vod_c" +
      "ommon.proto\032.byteplus/vod/business/vod_s" +
      "mart_strategy.proto\032+byteplus/vod/busine" +
      "ss/vod_apps_manage.proto\032\'byteplus/vod/b" +
      "usiness/vod_measure.proto\"\246\001\n\031VodGetAllP" +
      "layInfoResponse\022E\n\020ResponseMetadata\030\001 \001(" +
      "\0132+.Byteplus.Base.Models.Base.ResponseMe" +
      "tadata\022B\n\006Result\030\002 \001(\01322.Byteplus.Vod.Mo" +
      "dels.Business.VodAllPlayInfoResult\"\237\001\n\026V" +
      "odGetPlayInfoResponse\022E\n\020ResponseMetadat" +
      "a\030\001 \001(\0132+.Byteplus.Base.Models.Base.Resp" +
      "onseMetadata\022>\n\006Result\030\002 \001(\0132..Byteplus." +
      "Vod.Models.Business.VodPlayInfoModel\"\263\001\n" +
      "\036VodGetOriginalPlayInfoResponse\022E\n\020Respo" +
      "nseMetadata\030\001 \001(\0132+.Byteplus.Base.Models" +
      ".Base.ResponseMetadata\022J\n\006Result\030\002 \001(\0132:" +
      ".Byteplus.Vod.Models.Business.VodGetOrig" +
      "inalPlayInfoResult\"\267\001\n VodGetPrivateDrmP" +
      "layAuthResponse\022E\n\020ResponseMetadata\030\001 \001(" +
      "\0132+.Byteplus.Base.Models.Base.ResponseMe" +
      "tadata\022L\n\006Result\030\002 \001(\0132<.Byteplus.Vod.Mo" +
      "dels.Business.VodGetPrivateDrmPlayAuthRe" +
      "sult\"\263\001\n\036VodGetHlsDecryptionKeyResponse\022" +
      "E\n\020ResponseMetadata\030\001 \001(\0132+.Byteplus.Bas" +
      "e.Models.Base.ResponseMetadata\022J\n\006Result" +
      "\030\002 \001(\0132:.Byteplus.Vod.Models.Business.Vo" +
      "dGetHlsDecryptionKeyResult\"\317\001\n,VodGetPla" +
      "yInfoWithLiveTimeShiftSceneResponse\022E\n\020R" +
      "esponseMetadata\030\001 \001(\0132+.Byteplus.Base.Mo" +
      "dels.Base.ResponseMetadata\022X\n\006Result\030\002 \001" +
      "(\0132H.Byteplus.Vod.Models.Business.VodGet" +
      "PlayInfoWithLiveTimeShiftSceneResult\"\234\001\n" +
      "\026VodUploadMediaResponse\022E\n\020ResponseMetad" +
      "ata\030\001 \001(\0132+.Byteplus.Base.Models.Base.Re" +
      "sponseMetadata\022;\n\006Result\030\002 \001(\0132+.Byteplu" +
      "s.Vod.Models.Business.VodCommitData\"\243\001\n\036" +
      "VodQueryUploadTaskInfoResponse\022E\n\020Respon" +
      "seMetadata\030\001 \001(\0132+.Byteplus.Base.Models." +
      "Base.ResponseMetadata\022:\n\006Result\030\002 \001(\0132*." +
      "Byteplus.Vod.Models.Business.VodQueryDat" +
      "a\"\237\001\n\024VodUrlUploadResponse\022E\n\020ResponseMe" +
      "tadata\030\001 \001(\0132+.Byteplus.Base.Models.Base" +
      ".ResponseMetadata\022@\n\006Result\030\002 \001(\01320.Byte" +
      "plus.Vod.Models.Business.VodUrlResponseD" +
      "ata\"\253\001\n\032VodApplyUploadInfoResponse\022E\n\020Re" +
      "sponseMetadata\030\001 \001(\0132+.Byteplus.Base.Mod" +
      "els.Base.ResponseMetadata\022F\n\006Result\030\002 \001(" +
      "\01326.Byteplus.Vod.Models.Business.VodAppl" +
      "yUploadInfoResult\"\255\001\n\033VodCommitUploadInf" +
      "oResponse\022E\n\020ResponseMetadata\030\001 \001(\0132+.By" +
      "teplus.Base.Models.Base.ResponseMetadata" +
      "\022G\n\006Result\030\002 \001(\01327.Byteplus.Vod.Models.B" +
      "usiness.VodCommitUploadInfoResult\"\245\001\n\030Vo" +
      "dGetMediaInfosResponse\022E\n\020ResponseMetada" +
      "ta\030\001 \001(\0132+.Byteplus.Base.Models.Base.Res" +
      "ponseMetadata\022B\n\006Result\030\002 \001(\01322.Byteplus" +
      ".Vod.Models.Business.VodGetMediaInfosDat" +
      "a\"c\n\032VodUpdateMediaInfoResponse\022E\n\020Respo" +
      "nseMetadata\030\001 \001(\0132+.Byteplus.Base.Models" +
      ".Base.ResponseMetadata\"\253\001\n\037VodGetRecomme" +
      "ndedPosterResponse\022E\n\020ResponseMetadata\030\001" +
      " \001(\0132+.Byteplus.Base.Models.Base.Respons" +
      "eMetadata\022A\n\006Result\030\002 \001(\01321.Byteplus.Vod" +
      ".Models.Business.VodGetRecPosterData\"l\n#" +
      "VodUpdateMediaPublishStatusResponse\022E\n\020R" +
      "esponseMetadata\030\001 \001(\0132+.Byteplus.Base.Mo" +
      "dels.Base.ResponseMetadata\"\271\001\n\"VodUpdate" +
      "MediaStorageClassResponse\022E\n\020ResponseMet" +
      "adata\030\001 \001(\0132+.Byteplus.Base.Models.Base." +
      "ResponseMetadata\022L\n\006Result\030\002 \001(\0132<.Bytep" +
      "lus.Vod.Models.Business.VodUpdateMediaSt" +
      "orageClassData\"\241\001\n\026VodDeleteMediaRespons" +
      "e\022E\n\020ResponseMetadata\030\001 \001(\0132+.Byteplus.B" +
      "ase.Models.Base.ResponseMetadata\022@\n\006Resu" +
      "lt\030\002 \001(\01320.Byteplus.Vod.Models.Business." +
      "VodDeleteMediaData\"\253\001\n\033VodDeleteTranscod" +
      "esResponse\022E\n\020ResponseMetadata\030\001 \001(\0132+.B" +
      "yteplus.Base.Models.Base.ResponseMetadat" +
      "a\022E\n\006Result\030\002 \001(\01325.Byteplus.Vod.Models." +
      "Business.VodDeleteTranscodesData\"\243\001\n\027Vod" +
      "GetMediaListResponse\022E\n\020ResponseMetadata" +
      "\030\001 \001(\0132+.Byteplus.Base.Models.Base.Respo" +
      "nseMetadata\022A\n\006Result\030\002 \001(\01321.Byteplus.V" +
      "od.Models.Business.VodGetMediaListData\"\261" +
      "\001\n\036VodGetSubtitleInfoListResponse\022E\n\020Res" +
      "ponseMetadata\030\001 \001(\0132+.Byteplus.Base.Mode" +
      "ls.Base.ResponseMetadata\022H\n\006Result\030\002 \001(\013" +
      "28.Byteplus.Vod.Models.Business.VodGetSu" +
      "btitleInfoListData\"\263\001\n\037VodUpdateSubtitle" +
      "StatusResponse\022E\n\020ResponseMetadata\030\001 \001(\013" +
      "2+.Byteplus.Base.Models.Base.ResponseMet" +
      "adata\022I\n\006Result\030\002 \001(\01329.Byteplus.Vod.Mod" +
      "els.Business.VodUpdateSubtitleStatusData" +
      "\"f\n\035VodUpdateSubtitleInfoResponse\022E\n\020Res" +
      "ponseMetadata\030\001 \001(\0132+.Byteplus.Base.Mode" +
      "ls.Base.ResponseMetadata\"\264\001\n!VodGetAudit" +
      "FramesForAuditResponse\022E\n\020ResponseMetada" +
      "ta\030\001 \001(\0132+.Byteplus.Base.Models.Base.Res" +
      "ponseMetadata\022H\n\006Result\030\002 \001(\01328.Byteplus" +
      ".Vod.Models.Business.VodGetFramesForAudi" +
      "tResult\"\261\001\n\036VodGetMLFramesForAuditRespon" +
      "se\022E\n\020ResponseMetadata\030\001 \001(\0132+.Byteplus." +
      "Base.Models.Base.ResponseMetadata\022H\n\006Res" +
      "ult\030\002 \001(\01328.Byteplus.Vod.Models.Business" +
      ".VodGetFramesForAuditResult\"\273\001\n\"VodGetBe" +
      "tterFramesForAuditResponse\022E\n\020ResponseMe" +
      "tadata\030\001 \001(\0132+.Byteplus.Base.Models.Base" +
      ".ResponseMetadata\022N\n\006Result\030\002 \001(\0132>.Byte" +
      "plus.Vod.Models.Business.VodGetBetterFra" +
      "mesForAuditResult\"\265\001\n\037VodGetAudioInfoFor" +
      "AuditResponse\022E\n\020ResponseMetadata\030\001 \001(\0132" +
      "+.Byteplus.Base.Models.Base.ResponseMeta" +
      "data\022K\n\006Result\030\002 \001(\0132;.Byteplus.Vod.Mode" +
      "ls.Business.VodGetAudioInfoForAuditResul" +
      "t\"\327\001\n0VodGetAutomaticSpeechRecognitionFo" +
      "rAuditResponse\022E\n\020ResponseMetadata\030\001 \001(\013" +
      "2+.Byteplus.Base.Models.Base.ResponseMet" +
      "adata\022\\\n\006Result\030\002 \001(\0132L.Byteplus.Vod.Mod" +
      "els.Business.VodGetAutomaticSpeechRecogn" +
      "itionForAuditResult\"\311\001\n)VodGetAudioEvent" +
      "DetectionForAuditResponse\022E\n\020ResponseMet" +
      "adata\030\001 \001(\0132+.Byteplus.Base.Models.Base." +
      "ResponseMetadata\022U\n\006Result\030\002 \001(\0132E.Bytep" +
      "lus.Vod.Models.Business.VodGetAudioEvent" +
      "DetectionForAuditResult\"\275\001\n$VodCreateVid" +
      "eoClassificationResponse\022E\n\020ResponseMeta" +
      "data\030\001 \001(\0132+.Byteplus.Base.Models.Base.R" +
      "esponseMetadata\022N\n\006Result\030\002 \001(\0132>.Bytepl" +
      "us.Vod.Models.Business.VodCreateVideoCla" +
      "ssificationData\"m\n$VodUpdateVideoClassif" +
      "icationResponse\022E\n\020ResponseMetadata\030\001 \001(" +
      "\0132+.Byteplus.Base.Models.Base.ResponseMe" +
      "tadata\"m\n$VodDeleteVideoClassificationRe" +
      "sponse\022E\n\020ResponseMetadata\030\001 \001(\0132+.Bytep" +
      "lus.Base.Models.Base.ResponseMetadata\"\267\001" +
      "\n#VodListVideoClassificationsResponse\022E\n" +
      "\020ResponseMetadata\030\001 \001(\0132+.Byteplus.Base." +
      "Models.Base.ResponseMetadata\022I\n\006Result\030\002" +
      " \001(\01329.Byteplus.Vod.Models.Business.VodV" +
      "ideoClassificationsData\"\240\001\n\030VodListSnaps" +
      "hotsResponse\022E\n\020ResponseMetadata\030\001 \001(\0132+" +
      ".Byteplus.Base.Models.Base.ResponseMetad" +
      "ata\022=\n\006Result\030\002 \001(\0132-.Byteplus.Vod.Model" +
      "s.Business.VodSnapshotData\"\243\001\n\026VodGetFil" +
      "eListResponse\022E\n\020ResponseMetadata\030\001 \001(\0132" +
      "+.Byteplus.Base.Models.Base.ResponseMeta" +
      "data\022B\n\006Result\030\002 \001(\01322.Byteplus.Vod.Mode" +
      "ls.Business.VodGetMediaInfosData\"h\n\037VodE" +
      "xtractMediaMetaTaskResponse\022E\n\020ResponseM" +
      "etadata\030\001 \001(\0132+.Byteplus.Base.Models.Bas" +
      "e.ResponseMetadata\"\247\001\n\030VodStartWorkflowR" +
      "esponse\022E\n\020ResponseMetadata\030\001 \001(\0132+.Byte" +
      "plus.Base.Models.Base.ResponseMetadata\022D" +
      "\n\006Result\030\002 \001(\01324.Byteplus.Vod.Models.Bus" +
      "iness.VodStartWorkflowResult\"\252\001\n\"VodRetr" +
      "ieveTranscodeResultResponse\022E\n\020ResponseM" +
      "etadata\030\001 \001(\0132+.Byteplus.Base.Models.Bas" +
      "e.ResponseMetadata\022=\n\006Result\030\002 \001(\0132-.Byt" +
      "eplus.Vod.Models.Business.TranscodeResul" +
      "t\"\267\001\n VodListWorkflowExecutionResponse\022E" +
      "\n\020ResponseMetadata\030\001 \001(\0132+.Byteplus.Base" +
      ".Models.Base.ResponseMetadata\022L\n\006Result\030" +
      "\002 \001(\0132<.Byteplus.Vod.Models.Business.Vod" +
      "ListWorkflowExecutionResult\"\301\001\n%VodGetWo" +
      "rkflowExecutionDetailResponse\022E\n\020Respons" +
      "eMetadata\030\001 \001(\0132+.Byteplus.Base.Models.B" +
      "ase.ResponseMetadata\022Q\n\006Result\030\002 \001(\0132A.B" +
      "yteplus.Vod.Models.Business.VodGetWorkfl" +
      "owExecutionDetailResult\"\257\001\n%VodGetWorkfl" +
      "owExecutionStatusResponse\022E\n\020ResponseMet" +
      "adata\030\001 \001(\0132+.Byteplus.Base.Models.Base." +
      "ResponseMetadata\022?\n\006Result\030\002 \001(\0132/.Bytep" +
      "lus.Vod.Models.Business.WorkflowExecutio" +
      "n\"\246\001\n\034VodGetWorkflowResultResponse\022E\n\020Re" +
      "sponseMetadata\030\001 \001(\0132+.Byteplus.Base.Mod" +
      "els.Base.ResponseMetadata\022?\n\006Result\030\002 \001(" +
      "\0132/.Byteplus.Vod.Models.Business.VodWork" +
      "flowResult\"\274\001\n$VodSubmitDirectEditTaskAs" +
      "yncResponse\022E\n\020ResponseMetadata\030\001 \001(\0132+." +
      "Byteplus.Base.Models.Base.ResponseMetada" +
      "ta\022M\n\006Result\030\002 \001(\0132=.Byteplus.Vod.Models" +
      ".Business.SubmitDirectEditTaskAsyncResul" +
      "t\"\256\001\n VodGetDirectEditProgressResponse\022E" +
      "\n\020ResponseMetadata\030\001 \001(\0132+.Byteplus.Base" +
      ".Models.Base.ResponseMetadata\022C\n\006Result\030" +
      "\002 \001(\01323.Byteplus.Vod.Models.Business.Get" +
      "DirectEditProgress\"\252\001\n\036VodGetDirectEditR" +
      "esultResponse\022E\n\020ResponseMetadata\030\001 \001(\0132" +
      "+.Byteplus.Base.Models.Base.ResponseMeta" +
      "data\022A\n\006Result\030\002 \003(\01321.Byteplus.Vod.Mode" +
      "ls.Business.GetDirectEditResult\"_\n\026VodCr" +
      "eateSpaceResponse\022E\n\020ResponseMetadata\030\001 " +
      "\001(\0132+.Byteplus.Base.Models.Base.Response" +
      "Metadata\"\231\001\n\024VodListSpaceResponse\022E\n\020Res" +
      "ponseMetadata\030\001 \001(\0132+.Byteplus.Base.Mode" +
      "ls.Base.ResponseMetadata\022:\n\006Result\030\002 \003(\013" +
      "2*.Byteplus.Vod.Models.Business.VodSpace" +
      "Info\"\236\001\n\031VodGetSpaceDetailResponse\022E\n\020Re" +
      "sponseMetadata\030\001 \001(\0132+.Byteplus.Base.Mod" +
      "els.Base.ResponseMetadata\022:\n\006Result\030\002 \001(" +
      "\0132*.Byteplus.Vod.Models.Business.VodSpac" +
      "eInfo\"_\n\026VodUpdateSpaceResponse\022E\n\020Respo" +
      "nseMetadata\030\001 \001(\0132+.Byteplus.Base.Models" +
      ".Base.ResponseMetadata\"k\n\"VodUpdateSpace" +
      "UploadConfigResponse\022E\n\020ResponseMetadata" +
      "\030\001 \001(\0132+.Byteplus.Base.Models.Base.Respo" +
      "nseMetadata\"\303\001\n&VodDescribeVodSpaceStora" +
      "geDataResponse\022E\n\020ResponseMetadata\030\001 \001(\013" +
      "2+.Byteplus.Base.Models.Base.ResponseMet" +
      "adata\022R\n\006Result\030\002 \001(\0132B.Byteplus.Vod.Mod" +
      "els.Business.VodDescribeVodSpaceStorageD" +
      "ataResult\"\241\001\n\025VodListDomainResponse\022E\n\020R" +
      "esponseMetadata\030\001 \001(\0132+.Byteplus.Base.Mo" +
      "dels.Base.ResponseMetadata\022A\n\006Result\030\002 \001" +
      "(\01321.Byteplus.Vod.Models.Business.VodDom" +
      "ainConfigInfo\"\256\001\n\037VodCreateCdnRefreshTas" +
      "kResponse\022E\n\020ResponseMetadata\030\001 \001(\0132+.By" +
      "teplus.Base.Models.Base.ResponseMetadata" +
      "\022D\n\006Result\030\002 \001(\01324.Byteplus.Vod.Models.B" +
      "usiness.VodCreateCdnTaskResult\"\256\001\n\037VodCr" +
      "eateCdnPreloadTaskResponse\022E\n\020ResponseMe" +
      "tadata\030\001 \001(\0132+.Byteplus.Base.Models.Base" +
      ".ResponseMetadata\022D\n\006Result\030\002 \001(\01324.Byte" +
      "plus.Vod.Models.Business.VodCreateCdnTas" +
      "kResult\"\240\001\n\027VodListCdnTasksResponse\022E\n\020R" +
      "esponseMetadata\030\001 \001(\0132+.Byteplus.Base.Mo" +
      "dels.Base.ResponseMetadata\022>\n\006Result\030\002 \001" +
      "(\0132..Byteplus.Vod.Models.Business.VodCdn" +
      "TaskResult\"\255\001\n\033VodListCdnAccessLogRespon" +
      "se\022E\n\020ResponseMetadata\030\001 \001(\0132+.Byteplus." +
      "Base.Models.Base.ResponseMetadata\022G\n\006Res" +
      "ult\030\002 \001(\01327.Byteplus.Vod.Models.Business" +
      ".VodListCdnAccessLogResult\"\263\001\n\036VodListCd" +
      "nTopAccessUrlResponse\022E\n\020ResponseMetadat" +
      "a\030\001 \001(\0132+.Byteplus.Base.Models.Base.Resp" +
      "onseMetadata\022J\n\006Result\030\002 \001(\0132:.Byteplus." +
      "Vod.Models.Business.VodListCdnTopAccessU" +
      "rlResult\"\311\001\n)VodDescribeVodDomainBandwid" +
      "thDataResponse\022E\n\020ResponseMetadata\030\001 \001(\013" +
      "2+.Byteplus.Base.Models.Base.ResponseMet" +
      "adata\022U\n\006Result\030\002 \001(\0132E.Byteplus.Vod.Mod" +
      "els.Business.VodDescribeVodDomainBandwid" +
      "thDataResult\"\263\001\n\036VodCdnStatisticsCommonR" +
      "esponse\022E\n\020ResponseMetadata\030\001 \001(\0132+.Byte" +
      "plus.Base.Models.Base.ResponseMetadata\022J" +
      "\n\006Result\030\002 \001(\0132:.Byteplus.Vod.Models.Bus" +
      "iness.VodCdnStatisticsCommonResult\"\236\001\n\031V" +
      "odDescribeIPInfoResponse\022E\n\020ResponseMeta" +
      "data\030\001 \001(\0132+.Byteplus.Base.Models.Base.R" +
      "esponseMetadata\022:\n\006Result\030\002 \003(\0132*.Bytepl" +
      "us.Vod.Models.Business.VodCdnIpInfo\"\305\001\n\'" +
      "VodDescribeVodDomainTrafficDataResponse\022" +
      "E\n\020ResponseMetadata\030\001 \001(\0132+.Byteplus.Bas" +
      "e.Models.Base.ResponseMetadata\022S\n\006Result" +
      "\030\002 \001(\0132C.Byteplus.Vod.Models.Business.Vo" +
      "dDescribeVodDomainTrafficDataResult\"\255\001\n\033" +
      "VodSubmitBlockTasksResponse\022E\n\020ResponseM" +
      "etadata\030\001 \001(\0132+.Byteplus.Base.Models.Bas" +
      "e.ResponseMetadata\022G\n\006Result\030\002 \001(\01327.Byt" +
      "eplus.Vod.Models.Business.VodSubmitBlock" +
      "TasksResult\"\265\001\n\037VodGetContentBlockTasksR" +
      "esponse\022E\n\020ResponseMetadata\030\001 \001(\0132+.Byte" +
      "plus.Base.Models.Base.ResponseMetadata\022K" +
      "\n\006Result\030\002 \001(\0132;.Byteplus.Vod.Models.Bus" +
      "iness.VodGetContentBlockTasksResult\"b\n\031V" +
      "odCreateDomainV2Response\022E\n\020ResponseMeta" +
      "data\030\001 \001(\0132+.Byteplus.Base.Models.Base.R" +
      "esponseMetadata\"h\n\037VodUpdateDomainExpire" +
      "V2Response\022E\n\020ResponseMetadata\030\001 \001(\0132+.B" +
      "yteplus.Base.Models.Base.ResponseMetadat" +
      "a\"l\n#VodUpdateDomainAuthConfigV2Response" +
      "\022E\n\020ResponseMetadata\030\001 \001(\0132+.Byteplus.Ba" +
      "se.Models.Base.ResponseMetadata\"k\n\"VodAd" +
      "dCallbackSubscriptionResponse\022E\n\020Respons" +
      "eMetadata\030\001 \001(\0132+.Byteplus.Base.Models.B" +
      "ase.ResponseMetadata\"d\n\033VodSetCallbackEv" +
      "entResponse\022E\n\020ResponseMetadata\030\001 \001(\0132+." +
      "Byteplus.Base.Models.Base.ResponseMetada" +
      "ta\"\305\001\n\'VodGetSmartStrategyLitePlayInfoRe" +
      "sponse\022E\n\020ResponseMetadata\030\001 \001(\0132+.Bytep" +
      "lus.Base.Models.Base.ResponseMetadata\022S\n" +
      "\006Result\030\002 \001(\0132C.Byteplus.Vod.Models.Busi" +
      "ness.VodGetSmartStrategyLitePlayInfoResu" +
      "lt\"\241\001\n\025VodGetAppInfoResponse\022E\n\020Response" +
      "Metadata\030\001 \001(\0132+.Byteplus.Base.Models.Ba" +
      "se.ResponseMetadata\022A\n\006Result\030\002 \001(\01321.By" +
      "teplus.Vod.Models.Business.VodGetAppInfo" +
      "Result\"\301\001\n%DescribeVodSpaceTranscodeData" +
      "Response\022E\n\020ResponseMetadata\030\001 \001(\0132+.Byt" +
      "eplus.Base.Models.Base.ResponseMetadata\022" +
      "Q\n\006Result\030\002 \001(\0132A.Byteplus.Vod.Models.Bu" +
      "siness.DescribeVodSpaceTranscodeDataResu" +
      "lt\"\277\001\n$DescribeVodSpaceAIStatisDataRespo" +
      "nse\022E\n\020ResponseMetadata\030\001 \001(\0132+.Byteplus" +
      ".Base.Models.Base.ResponseMetadata\022P\n\006Re" +
      "sult\030\002 \001(\0132@.Byteplus.Vod.Models.Busines" +
      "s.DescribeVodSpaceAIStatisDataResult\"\313\001\n" +
      "*DescribeVodSpaceSubtitleStatisDataRespo" +
      "nse\022E\n\020ResponseMetadata\030\001 \001(\0132+.Byteplus" +
      ".Base.Models.Base.ResponseMetadata\022V\n\006Re" +
      "sult\030\002 \001(\0132F.Byteplus.Vod.Models.Busines" +
      "s.DescribeVodSpaceSubtitleStatisDataResu" +
      "lt\"\307\001\n(DescribeVodSpaceDetectStatisDataR" +
      "esponse\022E\n\020ResponseMetadata\030\001 \001(\0132+.Byte" +
      "plus.Base.Models.Base.ResponseMetadata\022T" +
      "\n\006Result\030\002 \001(\0132D.Byteplus.Vod.Models.Bus" +
      "iness.DescribeVodSpaceDetectStatisDataRe" +
      "sult\"\265\001\n\037DescribeVodSnapshotDataResponse" +
      "\022E\n\020ResponseMetadata\030\001 \001(\0132+.Byteplus.Ba" +
      "se.Models.Base.ResponseMetadata\022K\n\006Resul" +
      "t\030\002 \001(\0132;.Byteplus.Vod.Models.Business.D" +
      "escribeVodSnapshotDataResult\"\313\001\n*Describ" +
      "eVodSpaceWorkflowDetailDataResponse\022E\n\020R" +
      "esponseMetadata\030\001 \001(\0132+.Byteplus.Base.Mo" +
      "dels.Base.ResponseMetadata\022V\n\006Result\030\002 \001" +
      "(\0132F.Byteplus.Vod.Models.Business.Descri" +
      "beVodSpaceWorkflowDetailDataResult\"\303\001\n&D" +
      "escribeVodSpaceEditDetailDataResponse\022E\n" +
      "\020ResponseMetadata\030\001 \001(\0132+.Byteplus.Base." +
      "Models.Base.ResponseMetadata\022R\n\006Result\030\002" +
      " \001(\0132B.Byteplus.Vod.Models.Business.Desc" +
      "ribeVodSpaceEditDetailDataResult\"\303\001\n&Des" +
      "cribeVodPlayFileLogByDomainResponse\022E\n\020R" +
      "esponseMetadata\030\001 \001(\0132+.Byteplus.Base.Mo" +
      "dels.Base.ResponseMetadata\022R\n\006Result\030\002 \001" +
      "(\0132B.Byteplus.Vod.Models.Business.Descri" +
      "beVodPlayFileLogByDomainResult\"\265\001\n\037VodSu" +
      "bmitBlockMediaTaskResponse\022E\n\020ResponseMe" +
      "tadata\030\001 \001(\0132+.Byteplus.Base.Models.Base" +
      ".ResponseMetadata\022K\n\006Result\030\002 \001(\0132;.Byte" +
      "plus.Vod.Models.Business.VodSubmitBlockM" +
      "ediaTaskResult\"\271\001\n!VodSubmitUnblockMedia" +
      "TaskResponse\022E\n\020ResponseMetadata\030\001 \001(\0132+" +
      ".Byteplus.Base.Models.Base.ResponseMetad" +
      "ata\022M\n\006Result\030\002 \001(\0132=.Byteplus.Vod.Model" +
      "s.Business.VodSubmitUnblockMediaTaskResu" +
      "lt\"\267\001\n VodQueryMediaBlockStatusResponse\022" +
      "E\n\020ResponseMetadata\030\001 \001(\0132+.Byteplus.Bas" +
      "e.Models.Base.ResponseMetadata\022L\n\006Result" +
      "\030\002 \001(\0132<.Byteplus.Vod.Models.Business.Vo" +
      "dQueryMediaBlockStatusResult\"\251\001\n\031VodCrea" +
      "tePlaylistResponse\022E\n\020ResponseMetadata\030\001" +
      " \001(\0132+.Byteplus.Base.Models.Base.Respons" +
      "eMetadata\022E\n\006Result\030\002 \001(\01325.Byteplus.Vod" +
      ".Models.Business.VodCreatePlaylistResult" +
      "\"\245\001\n\027VodGetPlaylistsResponse\022E\n\020Response" +
      "Metadata\030\001 \001(\0132+.Byteplus.Base.Models.Ba" +
      "se.ResponseMetadata\022C\n\006Result\030\002 \001(\01323.By" +
      "teplus.Vod.Models.Business.VodGetPlaylis" +
      "tsResult\"b\n\031VodUpdatePlaylistResponse\022E\n" +
      "\020ResponseMetadata\030\001 \001(\0132+.Byteplus.Base." +
      "Models.Base.ResponseMetadata\"b\n\031VodDelet" +
      "ePlaylistResponse\022E\n\020ResponseMetadata\030\001 " +
      "\001(\0132+.Byteplus.Base.Models.Base.Response" +
      "MetadataB\330\001\n\'com.byteplus.service.vod.mo" +
      "del.responseB\013VodResponseP\001ZGgithub.com/" +
      "byteplus-sdk/byteplus-sdk-golang/service" +
      "/vod/models/response\240\001\001\330\001\001\312\002$Byteplus\\Se" +
      "rvice\\Vod\\Models\\Response\342\002\'Byteplus\\Ser" +
      "vice\\Vod\\Models\\GPBMetadatab\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.byteplus.service.base.model.base.Base.getDescriptor(),
          com.byteplus.service.vod.model.business.VodPlay.getDescriptor(),
          com.byteplus.service.vod.model.business.VodMedia.getDescriptor(),
          com.byteplus.service.vod.model.business.VodUpload.getDescriptor(),
          com.byteplus.service.vod.model.business.VodWorkflow.getDescriptor(),
          com.byteplus.service.vod.model.business.VodEdit.getDescriptor(),
          com.byteplus.service.vod.model.business.VodSpace.getDescriptor(),
          com.byteplus.service.vod.model.business.VodCdn.getDescriptor(),
          com.byteplus.service.vod.model.business.VodCommon.getDescriptor(),
          com.byteplus.service.vod.model.business.VodSmartStrategy.getDescriptor(),
          com.byteplus.service.vod.model.business.VodAppsManage.getDescriptor(),
          com.byteplus.service.vod.model.business.VodMeasure.getDescriptor(),
        });
    internal_static_Byteplus_Vod_Models_Response_VodGetAllPlayInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Byteplus_Vod_Models_Response_VodGetAllPlayInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodGetAllPlayInfoResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodGetPlayInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Byteplus_Vod_Models_Response_VodGetPlayInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodGetPlayInfoResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodGetOriginalPlayInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Byteplus_Vod_Models_Response_VodGetOriginalPlayInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodGetOriginalPlayInfoResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodGetPrivateDrmPlayAuthResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Byteplus_Vod_Models_Response_VodGetPrivateDrmPlayAuthResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodGetPrivateDrmPlayAuthResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodGetHlsDecryptionKeyResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Byteplus_Vod_Models_Response_VodGetHlsDecryptionKeyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodGetHlsDecryptionKeyResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodGetPlayInfoWithLiveTimeShiftSceneResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Byteplus_Vod_Models_Response_VodGetPlayInfoWithLiveTimeShiftSceneResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodGetPlayInfoWithLiveTimeShiftSceneResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodUploadMediaResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_Byteplus_Vod_Models_Response_VodUploadMediaResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodUploadMediaResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodQueryUploadTaskInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_Byteplus_Vod_Models_Response_VodQueryUploadTaskInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodQueryUploadTaskInfoResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodUrlUploadResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_Byteplus_Vod_Models_Response_VodUrlUploadResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodUrlUploadResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodApplyUploadInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_Byteplus_Vod_Models_Response_VodApplyUploadInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodApplyUploadInfoResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodCommitUploadInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_Byteplus_Vod_Models_Response_VodCommitUploadInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodCommitUploadInfoResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodGetMediaInfosResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_Byteplus_Vod_Models_Response_VodGetMediaInfosResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodGetMediaInfosResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodUpdateMediaInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_Byteplus_Vod_Models_Response_VodUpdateMediaInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodUpdateMediaInfoResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", });
    internal_static_Byteplus_Vod_Models_Response_VodGetRecommendedPosterResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_Byteplus_Vod_Models_Response_VodGetRecommendedPosterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodGetRecommendedPosterResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodUpdateMediaPublishStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_Byteplus_Vod_Models_Response_VodUpdateMediaPublishStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodUpdateMediaPublishStatusResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", });
    internal_static_Byteplus_Vod_Models_Response_VodUpdateMediaStorageClassResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_Byteplus_Vod_Models_Response_VodUpdateMediaStorageClassResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodUpdateMediaStorageClassResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodDeleteMediaResponse_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_Byteplus_Vod_Models_Response_VodDeleteMediaResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodDeleteMediaResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodDeleteTranscodesResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_Byteplus_Vod_Models_Response_VodDeleteTranscodesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodDeleteTranscodesResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodGetMediaListResponse_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_Byteplus_Vod_Models_Response_VodGetMediaListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodGetMediaListResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodGetSubtitleInfoListResponse_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_Byteplus_Vod_Models_Response_VodGetSubtitleInfoListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodGetSubtitleInfoListResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodUpdateSubtitleStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_Byteplus_Vod_Models_Response_VodUpdateSubtitleStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodUpdateSubtitleStatusResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodUpdateSubtitleInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_Byteplus_Vod_Models_Response_VodUpdateSubtitleInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodUpdateSubtitleInfoResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", });
    internal_static_Byteplus_Vod_Models_Response_VodGetAuditFramesForAuditResponse_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_Byteplus_Vod_Models_Response_VodGetAuditFramesForAuditResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodGetAuditFramesForAuditResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodGetMLFramesForAuditResponse_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_Byteplus_Vod_Models_Response_VodGetMLFramesForAuditResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodGetMLFramesForAuditResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodGetBetterFramesForAuditResponse_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_Byteplus_Vod_Models_Response_VodGetBetterFramesForAuditResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodGetBetterFramesForAuditResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodGetAudioInfoForAuditResponse_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_Byteplus_Vod_Models_Response_VodGetAudioInfoForAuditResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodGetAudioInfoForAuditResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodGetAutomaticSpeechRecognitionForAuditResponse_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_Byteplus_Vod_Models_Response_VodGetAutomaticSpeechRecognitionForAuditResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodGetAutomaticSpeechRecognitionForAuditResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodGetAudioEventDetectionForAuditResponse_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_Byteplus_Vod_Models_Response_VodGetAudioEventDetectionForAuditResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodGetAudioEventDetectionForAuditResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodCreateVideoClassificationResponse_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_Byteplus_Vod_Models_Response_VodCreateVideoClassificationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodCreateVideoClassificationResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodUpdateVideoClassificationResponse_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_Byteplus_Vod_Models_Response_VodUpdateVideoClassificationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodUpdateVideoClassificationResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", });
    internal_static_Byteplus_Vod_Models_Response_VodDeleteVideoClassificationResponse_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_Byteplus_Vod_Models_Response_VodDeleteVideoClassificationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodDeleteVideoClassificationResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", });
    internal_static_Byteplus_Vod_Models_Response_VodListVideoClassificationsResponse_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_Byteplus_Vod_Models_Response_VodListVideoClassificationsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodListVideoClassificationsResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodListSnapshotsResponse_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_Byteplus_Vod_Models_Response_VodListSnapshotsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodListSnapshotsResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodGetFileListResponse_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_Byteplus_Vod_Models_Response_VodGetFileListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodGetFileListResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodExtractMediaMetaTaskResponse_descriptor =
      getDescriptor().getMessageTypes().get(34);
    internal_static_Byteplus_Vod_Models_Response_VodExtractMediaMetaTaskResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodExtractMediaMetaTaskResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", });
    internal_static_Byteplus_Vod_Models_Response_VodStartWorkflowResponse_descriptor =
      getDescriptor().getMessageTypes().get(35);
    internal_static_Byteplus_Vod_Models_Response_VodStartWorkflowResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodStartWorkflowResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodRetrieveTranscodeResultResponse_descriptor =
      getDescriptor().getMessageTypes().get(36);
    internal_static_Byteplus_Vod_Models_Response_VodRetrieveTranscodeResultResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodRetrieveTranscodeResultResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodListWorkflowExecutionResponse_descriptor =
      getDescriptor().getMessageTypes().get(37);
    internal_static_Byteplus_Vod_Models_Response_VodListWorkflowExecutionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodListWorkflowExecutionResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodGetWorkflowExecutionDetailResponse_descriptor =
      getDescriptor().getMessageTypes().get(38);
    internal_static_Byteplus_Vod_Models_Response_VodGetWorkflowExecutionDetailResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodGetWorkflowExecutionDetailResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodGetWorkflowExecutionStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(39);
    internal_static_Byteplus_Vod_Models_Response_VodGetWorkflowExecutionStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodGetWorkflowExecutionStatusResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodGetWorkflowResultResponse_descriptor =
      getDescriptor().getMessageTypes().get(40);
    internal_static_Byteplus_Vod_Models_Response_VodGetWorkflowResultResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodGetWorkflowResultResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodSubmitDirectEditTaskAsyncResponse_descriptor =
      getDescriptor().getMessageTypes().get(41);
    internal_static_Byteplus_Vod_Models_Response_VodSubmitDirectEditTaskAsyncResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodSubmitDirectEditTaskAsyncResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodGetDirectEditProgressResponse_descriptor =
      getDescriptor().getMessageTypes().get(42);
    internal_static_Byteplus_Vod_Models_Response_VodGetDirectEditProgressResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodGetDirectEditProgressResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodGetDirectEditResultResponse_descriptor =
      getDescriptor().getMessageTypes().get(43);
    internal_static_Byteplus_Vod_Models_Response_VodGetDirectEditResultResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodGetDirectEditResultResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodCreateSpaceResponse_descriptor =
      getDescriptor().getMessageTypes().get(44);
    internal_static_Byteplus_Vod_Models_Response_VodCreateSpaceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodCreateSpaceResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", });
    internal_static_Byteplus_Vod_Models_Response_VodListSpaceResponse_descriptor =
      getDescriptor().getMessageTypes().get(45);
    internal_static_Byteplus_Vod_Models_Response_VodListSpaceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodListSpaceResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodGetSpaceDetailResponse_descriptor =
      getDescriptor().getMessageTypes().get(46);
    internal_static_Byteplus_Vod_Models_Response_VodGetSpaceDetailResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodGetSpaceDetailResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodUpdateSpaceResponse_descriptor =
      getDescriptor().getMessageTypes().get(47);
    internal_static_Byteplus_Vod_Models_Response_VodUpdateSpaceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodUpdateSpaceResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", });
    internal_static_Byteplus_Vod_Models_Response_VodUpdateSpaceUploadConfigResponse_descriptor =
      getDescriptor().getMessageTypes().get(48);
    internal_static_Byteplus_Vod_Models_Response_VodUpdateSpaceUploadConfigResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodUpdateSpaceUploadConfigResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", });
    internal_static_Byteplus_Vod_Models_Response_VodDescribeVodSpaceStorageDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(49);
    internal_static_Byteplus_Vod_Models_Response_VodDescribeVodSpaceStorageDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodDescribeVodSpaceStorageDataResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodListDomainResponse_descriptor =
      getDescriptor().getMessageTypes().get(50);
    internal_static_Byteplus_Vod_Models_Response_VodListDomainResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodListDomainResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodCreateCdnRefreshTaskResponse_descriptor =
      getDescriptor().getMessageTypes().get(51);
    internal_static_Byteplus_Vod_Models_Response_VodCreateCdnRefreshTaskResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodCreateCdnRefreshTaskResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodCreateCdnPreloadTaskResponse_descriptor =
      getDescriptor().getMessageTypes().get(52);
    internal_static_Byteplus_Vod_Models_Response_VodCreateCdnPreloadTaskResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodCreateCdnPreloadTaskResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodListCdnTasksResponse_descriptor =
      getDescriptor().getMessageTypes().get(53);
    internal_static_Byteplus_Vod_Models_Response_VodListCdnTasksResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodListCdnTasksResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodListCdnAccessLogResponse_descriptor =
      getDescriptor().getMessageTypes().get(54);
    internal_static_Byteplus_Vod_Models_Response_VodListCdnAccessLogResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodListCdnAccessLogResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodListCdnTopAccessUrlResponse_descriptor =
      getDescriptor().getMessageTypes().get(55);
    internal_static_Byteplus_Vod_Models_Response_VodListCdnTopAccessUrlResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodListCdnTopAccessUrlResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodDescribeVodDomainBandwidthDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(56);
    internal_static_Byteplus_Vod_Models_Response_VodDescribeVodDomainBandwidthDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodDescribeVodDomainBandwidthDataResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodCdnStatisticsCommonResponse_descriptor =
      getDescriptor().getMessageTypes().get(57);
    internal_static_Byteplus_Vod_Models_Response_VodCdnStatisticsCommonResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodCdnStatisticsCommonResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodDescribeIPInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(58);
    internal_static_Byteplus_Vod_Models_Response_VodDescribeIPInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodDescribeIPInfoResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodDescribeVodDomainTrafficDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(59);
    internal_static_Byteplus_Vod_Models_Response_VodDescribeVodDomainTrafficDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodDescribeVodDomainTrafficDataResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodSubmitBlockTasksResponse_descriptor =
      getDescriptor().getMessageTypes().get(60);
    internal_static_Byteplus_Vod_Models_Response_VodSubmitBlockTasksResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodSubmitBlockTasksResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodGetContentBlockTasksResponse_descriptor =
      getDescriptor().getMessageTypes().get(61);
    internal_static_Byteplus_Vod_Models_Response_VodGetContentBlockTasksResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodGetContentBlockTasksResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodCreateDomainV2Response_descriptor =
      getDescriptor().getMessageTypes().get(62);
    internal_static_Byteplus_Vod_Models_Response_VodCreateDomainV2Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodCreateDomainV2Response_descriptor,
        new java.lang.String[] { "ResponseMetadata", });
    internal_static_Byteplus_Vod_Models_Response_VodUpdateDomainExpireV2Response_descriptor =
      getDescriptor().getMessageTypes().get(63);
    internal_static_Byteplus_Vod_Models_Response_VodUpdateDomainExpireV2Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodUpdateDomainExpireV2Response_descriptor,
        new java.lang.String[] { "ResponseMetadata", });
    internal_static_Byteplus_Vod_Models_Response_VodUpdateDomainAuthConfigV2Response_descriptor =
      getDescriptor().getMessageTypes().get(64);
    internal_static_Byteplus_Vod_Models_Response_VodUpdateDomainAuthConfigV2Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodUpdateDomainAuthConfigV2Response_descriptor,
        new java.lang.String[] { "ResponseMetadata", });
    internal_static_Byteplus_Vod_Models_Response_VodAddCallbackSubscriptionResponse_descriptor =
      getDescriptor().getMessageTypes().get(65);
    internal_static_Byteplus_Vod_Models_Response_VodAddCallbackSubscriptionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodAddCallbackSubscriptionResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", });
    internal_static_Byteplus_Vod_Models_Response_VodSetCallbackEventResponse_descriptor =
      getDescriptor().getMessageTypes().get(66);
    internal_static_Byteplus_Vod_Models_Response_VodSetCallbackEventResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodSetCallbackEventResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", });
    internal_static_Byteplus_Vod_Models_Response_VodGetSmartStrategyLitePlayInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(67);
    internal_static_Byteplus_Vod_Models_Response_VodGetSmartStrategyLitePlayInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodGetSmartStrategyLitePlayInfoResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodGetAppInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(68);
    internal_static_Byteplus_Vod_Models_Response_VodGetAppInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodGetAppInfoResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_DescribeVodSpaceTranscodeDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(69);
    internal_static_Byteplus_Vod_Models_Response_DescribeVodSpaceTranscodeDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_DescribeVodSpaceTranscodeDataResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_DescribeVodSpaceAIStatisDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(70);
    internal_static_Byteplus_Vod_Models_Response_DescribeVodSpaceAIStatisDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_DescribeVodSpaceAIStatisDataResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_DescribeVodSpaceSubtitleStatisDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(71);
    internal_static_Byteplus_Vod_Models_Response_DescribeVodSpaceSubtitleStatisDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_DescribeVodSpaceSubtitleStatisDataResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_DescribeVodSpaceDetectStatisDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(72);
    internal_static_Byteplus_Vod_Models_Response_DescribeVodSpaceDetectStatisDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_DescribeVodSpaceDetectStatisDataResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_DescribeVodSnapshotDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(73);
    internal_static_Byteplus_Vod_Models_Response_DescribeVodSnapshotDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_DescribeVodSnapshotDataResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_DescribeVodSpaceWorkflowDetailDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(74);
    internal_static_Byteplus_Vod_Models_Response_DescribeVodSpaceWorkflowDetailDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_DescribeVodSpaceWorkflowDetailDataResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_DescribeVodSpaceEditDetailDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(75);
    internal_static_Byteplus_Vod_Models_Response_DescribeVodSpaceEditDetailDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_DescribeVodSpaceEditDetailDataResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_DescribeVodPlayFileLogByDomainResponse_descriptor =
      getDescriptor().getMessageTypes().get(76);
    internal_static_Byteplus_Vod_Models_Response_DescribeVodPlayFileLogByDomainResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_DescribeVodPlayFileLogByDomainResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodSubmitBlockMediaTaskResponse_descriptor =
      getDescriptor().getMessageTypes().get(77);
    internal_static_Byteplus_Vod_Models_Response_VodSubmitBlockMediaTaskResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodSubmitBlockMediaTaskResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodSubmitUnblockMediaTaskResponse_descriptor =
      getDescriptor().getMessageTypes().get(78);
    internal_static_Byteplus_Vod_Models_Response_VodSubmitUnblockMediaTaskResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodSubmitUnblockMediaTaskResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodQueryMediaBlockStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(79);
    internal_static_Byteplus_Vod_Models_Response_VodQueryMediaBlockStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodQueryMediaBlockStatusResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodCreatePlaylistResponse_descriptor =
      getDescriptor().getMessageTypes().get(80);
    internal_static_Byteplus_Vod_Models_Response_VodCreatePlaylistResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodCreatePlaylistResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodGetPlaylistsResponse_descriptor =
      getDescriptor().getMessageTypes().get(81);
    internal_static_Byteplus_Vod_Models_Response_VodGetPlaylistsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodGetPlaylistsResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", "Result", });
    internal_static_Byteplus_Vod_Models_Response_VodUpdatePlaylistResponse_descriptor =
      getDescriptor().getMessageTypes().get(82);
    internal_static_Byteplus_Vod_Models_Response_VodUpdatePlaylistResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodUpdatePlaylistResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", });
    internal_static_Byteplus_Vod_Models_Response_VodDeletePlaylistResponse_descriptor =
      getDescriptor().getMessageTypes().get(83);
    internal_static_Byteplus_Vod_Models_Response_VodDeletePlaylistResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Vod_Models_Response_VodDeletePlaylistResponse_descriptor,
        new java.lang.String[] { "ResponseMetadata", });
    com.byteplus.service.base.model.base.Base.getDescriptor();
    com.byteplus.service.vod.model.business.VodPlay.getDescriptor();
    com.byteplus.service.vod.model.business.VodMedia.getDescriptor();
    com.byteplus.service.vod.model.business.VodUpload.getDescriptor();
    com.byteplus.service.vod.model.business.VodWorkflow.getDescriptor();
    com.byteplus.service.vod.model.business.VodEdit.getDescriptor();
    com.byteplus.service.vod.model.business.VodSpace.getDescriptor();
    com.byteplus.service.vod.model.business.VodCdn.getDescriptor();
    com.byteplus.service.vod.model.business.VodCommon.getDescriptor();
    com.byteplus.service.vod.model.business.VodSmartStrategy.getDescriptor();
    com.byteplus.service.vod.model.business.VodAppsManage.getDescriptor();
    com.byteplus.service.vod.model.business.VodMeasure.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
