// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vod/response/response_vod.proto

package com.byteplus.service.vod.model.response;

public interface VodUpdateMediaInfoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Byteplus.Vod.Models.Response.VodUpdateMediaInfoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Byteplus.Vod.Models.Base.ResponseMetadata ResponseMetadata = 1;</code>
   * @return Whether the responseMetadata field is set.
   */
  boolean hasResponseMetadata();
  /**
   * <code>.Byteplus.Vod.Models.Base.ResponseMetadata ResponseMetadata = 1;</code>
   * @return The responseMetadata.
   */
  com.byteplus.service.vod.model.base.ResponseMetadata getResponseMetadata();
  /**
   * <code>.Byteplus.Vod.Models.Base.ResponseMetadata ResponseMetadata = 1;</code>
   */
  com.byteplus.service.vod.model.base.ResponseMetadataOrBuilder getResponseMetadataOrBuilder();
}
