// Code generated by protoc-gen-byteplus-sdk
// source: createHlsDecryptionKey
// DO NOT EDIT!

package com.byteplus.example.vod.play;

import com.byteplus.service.vod.IVodService;
import com.byteplus.service.vod.impl.VodServiceImpl;
public class VodCreateHlsDecryptionKeyDemo {

    public static void main(String[] args) throws Exception {
        IVodService vodService = VodServiceImpl.getInstance();
        vodService.setAccessKey("your ak");
        vodService.setSecretKey("your sk");

        try {
            com.byteplus.service.vod.model.request.VodCreateHlsDecryptionKeyRequest.Builder reqBuilder = com.byteplus.service.vod.model.request.VodCreateHlsDecryptionKeyRequest.newBuilder();
			reqBuilder.setSpaceName("your SpaceName");
			
            com.byteplus.service.vod.model.response.VodCreateHlsDecryptionKeyResponse resp = vodService.createHlsDecryptionKey(reqBuilder.build());
            if (resp.getResponseMetadata().hasError()) {
                System.out.println(resp.getResponseMetadata().getError());
                System.exit(-1);
            }
            System.out.println(resp);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}