// Code generated by protoc-gen-byteplus-sdk
// source: listVideoClassifications
// DO NOT EDIT!

package com.byteplus.example.vod.media;

import com.byteplus.service.vod.IVodService;
import com.byteplus.service.vod.impl.VodServiceImpl;
public class VodListVideoClassificationsDemo {

    public static void main(String[] args) throws Exception {
        IVodService vodService = VodServiceImpl.getInstance();
        vodService.setAccessKey("your ak");
        vodService.setSecretKey("your sk");

        try {
            com.byteplus.service.vod.model.request.VodListVideoClassificationsRequest.Builder reqBuilder = com.byteplus.service.vod.model.request.VodListVideoClassificationsRequest.newBuilder();
			reqBuilder.setSpaceName("your SpaceName");
			reqBuilder.setClassificationId(0);
			
            com.byteplus.service.vod.model.response.VodListVideoClassificationsResponse resp = vodService.listVideoClassifications(reqBuilder.build());
            if (resp.getResponseMetadata().hasError()) {
                System.out.println(resp.getResponseMetadata().getError());
                System.exit(-1);
            }
            System.out.println(resp);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}