// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: byteplus/vod/request/request_vod.proto

package com.byteplus.service.vod.model.request;

public interface VodGetDirectEditProgressRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Byteplus.Vod.Models.Request.VodGetDirectEditProgressRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ReqId = 1;</code>
   * @return The reqId.
   */
  java.lang.String getReqId();
  /**
   * <code>string ReqId = 1;</code>
   * @return The bytes for reqId.
   */
  com.google.protobuf.ByteString
      getReqIdBytes();
}
