// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: byteplus/vod/request/request_vod.proto

package com.byteplus.service.vod.model.request;

public interface VodSetMirrorSrcRuleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Byteplus.Vod.Models.Request.VodSetMirrorSrcRuleRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string SpaceName = 1;</code>
   * @return The spaceName.
   */
  java.lang.String getSpaceName();
  /**
   * <code>string SpaceName = 1;</code>
   * @return The bytes for spaceName.
   */
  com.google.protobuf.ByteString
      getSpaceNameBytes();

  /**
   * <pre>
   * 不传id为创建镜像回源规则,传id为更新镜像回源规则,更新时,不允许更新来源域名
   * </pre>
   *
   * <code>.google.protobuf.StringValue Id = 2;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <pre>
   * 不传id为创建镜像回源规则,传id为更新镜像回源规则,更新时,不允许更新来源域名
   * </pre>
   *
   * <code>.google.protobuf.StringValue Id = 2;</code>
   * @return The id.
   */
  com.google.protobuf.StringValue getId();
  /**
   * <pre>
   * 不传id为创建镜像回源规则,传id为更新镜像回源规则,更新时,不允许更新来源域名
   * </pre>
   *
   * <code>.google.protobuf.StringValue Id = 2;</code>
   */
  com.google.protobuf.StringValueOrBuilder getIdOrBuilder();

  /**
   * <code>.Byteplus.Vod.Models.Business.MirrorSrcRule MirrorSrcRule = 3;</code>
   * @return Whether the mirrorSrcRule field is set.
   */
  boolean hasMirrorSrcRule();
  /**
   * <code>.Byteplus.Vod.Models.Business.MirrorSrcRule MirrorSrcRule = 3;</code>
   * @return The mirrorSrcRule.
   */
  com.byteplus.service.vod.model.business.MirrorSrcRule getMirrorSrcRule();
  /**
   * <code>.Byteplus.Vod.Models.Business.MirrorSrcRule MirrorSrcRule = 3;</code>
   */
  com.byteplus.service.vod.model.business.MirrorSrcRuleOrBuilder getMirrorSrcRuleOrBuilder();
}
