// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: byteplus/vod/request/request_vod.proto

package com.byteplus.service.vod.model.request;

public interface VodSetFairPlayCertInfoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Byteplus.Vod.Models.Request.VodSetFairPlayCertInfoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string SpaceName = 1;</code>
   * @return The spaceName.
   */
  java.lang.String getSpaceName();
  /**
   * <code>string SpaceName = 1;</code>
   * @return The bytes for spaceName.
   */
  com.google.protobuf.ByteString
      getSpaceNameBytes();

  /**
   * <code>string CertName = 2;</code>
   * @return The certName.
   */
  java.lang.String getCertName();
  /**
   * <code>string CertName = 2;</code>
   * @return The bytes for certName.
   */
  com.google.protobuf.ByteString
      getCertNameBytes();

  /**
   * <code>string CertFile = 3;</code>
   * @return The certFile.
   */
  java.lang.String getCertFile();
  /**
   * <code>string CertFile = 3;</code>
   * @return The bytes for certFile.
   */
  com.google.protobuf.ByteString
      getCertFileBytes();

  /**
   * <code>string PkFile = 4;</code>
   * @return The pkFile.
   */
  java.lang.String getPkFile();
  /**
   * <code>string PkFile = 4;</code>
   * @return The bytes for pkFile.
   */
  com.google.protobuf.ByteString
      getPkFileBytes();

  /**
   * <code>string CertFileName = 5;</code>
   * @return The certFileName.
   */
  java.lang.String getCertFileName();
  /**
   * <code>string CertFileName = 5;</code>
   * @return The bytes for certFileName.
   */
  com.google.protobuf.ByteString
      getCertFileNameBytes();

  /**
   * <code>string PkFileName = 6;</code>
   * @return The pkFileName.
   */
  java.lang.String getPkFileName();
  /**
   * <code>string PkFileName = 6;</code>
   * @return The bytes for pkFileName.
   */
  com.google.protobuf.ByteString
      getPkFileNameBytes();

  /**
   * <code>string PkPassword = 7;</code>
   * @return The pkPassword.
   */
  java.lang.String getPkPassword();
  /**
   * <code>string PkPassword = 7;</code>
   * @return The bytes for pkPassword.
   */
  com.google.protobuf.ByteString
      getPkPasswordBytes();

  /**
   * <code>string Ask = 8;</code>
   * @return The ask.
   */
  java.lang.String getAsk();
  /**
   * <code>string Ask = 8;</code>
   * @return The bytes for ask.
   */
  com.google.protobuf.ByteString
      getAskBytes();
}
