// Code generated by protoc-gen-byteplus-sdk
// source: retrieveTranscodeResult
// DO NOT EDIT!

package com.byteplus.example.vod.workflow;

import com.byteplus.service.vod.IVodService;
import com.byteplus.service.vod.impl.VodServiceImpl;
public class VodRetrieveTranscodeResultDemo {

    public static void main(String[] args) throws Exception {
        IVodService vodService = VodServiceImpl.getInstance();
        vodService.setAccessKey("your ak");
        vodService.setSecretKey("your sk");

        try {
            com.byteplus.service.vod.model.request.VodRetrieveTranscodeResultRequest.Builder reqBuilder = com.byteplus.service.vod.model.request.VodRetrieveTranscodeResultRequest.newBuilder();
			reqBuilder.setVid("your Vid");
			reqBuilder.setResultType("your ResultType");
			
            com.byteplus.service.vod.model.response.VodRetrieveTranscodeResultResponse resp = vodService.retrieveTranscodeResult(reqBuilder.build());
            if (resp.getResponseMetadata().hasError()) {
                System.out.println(resp.getResponseMetadata().getError());
                System.exit(-1);
            }
            System.out.println(resp);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}