// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: byteplus/base/base.proto

package com.byteplus.service.base.model.base;

public final class Base {
  private Base() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Base_Models_Base_ResponseMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Base_Models_Base_ResponseMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Byteplus_Base_Models_Base_ResponseError_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Byteplus_Base_Models_Base_ResponseError_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030byteplus/base/base.proto\022\031Byteplus.Bas" +
      "e.Models.Base\032 google/protobuf/descripto" +
      "r.proto\"\240\001\n\020ResponseMetadata\022\021\n\tRequestI" +
      "d\030\001 \001(\t\022\016\n\006Action\030\002 \001(\t\022\017\n\007Version\030\003 \001(\t" +
      "\022\017\n\007Service\030\004 \001(\t\022\016\n\006Region\030\005 \001(\t\0227\n\005Err" +
      "or\030\006 \001(\0132(.Byteplus.Base.Models.Base.Res" +
      "ponseError\".\n\rResponseError\022\014\n\004Code\030\001 \001(" +
      "\t\022\017\n\007Message\030\002 \001(\tB\314\001\n$com.byteplus.serv" +
      "ice.base.model.baseB\004BaseP\001ZDgithub.com/" +
      "byteplus-sdk/byteplus-sdk-golang/service" +
      "/base/models/base\240\001\001\330\001\001\302\002\000\312\002!Byteplus\\Se" +
      "rvice\\Base\\Models\\Base\342\002(Byteplus\\Servic" +
      "e\\Base\\Models\\GPBMetadatab\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    internal_static_Byteplus_Base_Models_Base_ResponseMetadata_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Byteplus_Base_Models_Base_ResponseMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Base_Models_Base_ResponseMetadata_descriptor,
        new java.lang.String[] { "RequestId", "Action", "Version", "Service", "Region", "Error", });
    internal_static_Byteplus_Base_Models_Base_ResponseError_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Byteplus_Base_Models_Base_ResponseError_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Byteplus_Base_Models_Base_ResponseError_descriptor,
        new java.lang.String[] { "Code", "Message", });
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
